import type { ArticlePhoto } from "./types";

function p(src: string, alt: string, caption: string): ArticlePhoto {
  return { src, alt, caption: `${caption} 示意图，不能单凭此图下肥。` };
}

function pair(slug: string, a1: string, c1: string, a2: string, c2: string): ArticlePhoto[] {
  return [
    p(`/images/articles/${slug}.jpg`, a1, c1),
    p(`/images/articles/${slug}-2.jpg`, a2, c2),
  ];
}

const COVER: Record<string, ArticlePhoto[]> = {
  "suan-hua": pair("suan-hua", "酸化地发僵发黄的麦苗", "酸化地苗弱叶黄、发僵", "酸化伤根根尖发褐", "根尖发褐、新根少"),
  "yan-jian": pair("yan-jian", "盐碱地土面白霜", "春季返盐，土面白霜、出苗不齐", "盐害叶缘焦枯", "叶缘焦，像被烫过"),
  "ban-jie": pair("ban-jie", "板结硬土块，锄头刨不动", "硬土块、根翻不上来", "板结土柱紧实无孔隙", "紧实土柱，水和根都难过"),
  "you-ji-zhi": [
    p("/images/articles/you-ji-zhi.jpg", "有机质低的浅色瘦土", "土色发浅、粉、结构差"),
    p("/images/healthy-soil.jpg", "有机质高的团粒土（健康对照）", "这是健康对照，不是本病。颜色深、能搓团又易散"),
  ],
  "que-dan": pair("que-dan", "下部老叶均匀发黄、新叶相对还绿", "缺氮：下部老叶匀黄，植株瘦", "缺氮植株瘦高不壮", "整株瘦、分蘖少"),
  "que-jia": pair("que-jia", "老叶叶缘焦枯像火燎", "缺钾：老叶边缘焦，向内卷", "缺钾叶缘焦从外向内", "叶缘焦枯向内发展"),
  "que-lin": pair("que-lin", "缺磷苗紫红发僵", "苗矮、叶暗绿带紫红", "缺磷根系短少", "根少、不发棵"),
  "que-tie": pair("que-tie", "新叶黄、叶脉还绿", "缺铁：新叶失绿，叶脉保持绿色", "果树缺铁黄化新梢", "顶端新叶更黄"),
  "que-xin": pair("que-xin", "玉米花白苗、节间缩短", "缺锌：脉间失绿、植株矮", "果树小叶簇生", "叶片变小、簇生"),
  "que-gai": pair("que-gai", "番茄脐腐、顶芽出问题", "缺钙：脐腐、生长点停", "缺钙裂果", "果实开裂、心叶边缘焦"),
  "que-mei": pair("que-mei", "老叶脉间黄、叶脉仍绿", "缺镁：老叶脉间黄", "缺镁从叶缘向内黄", "下部叶片先表现"),
  "que-peng": pair("que-peng", "花而不实、茎空心", "缺硼：花开了不结实", "裂茎空心", "茎裂、空心"),
  "que-meng": pair("que-meng", "新叶脉间失绿带褐斑", "缺锰：新叶脉间黄，常带褐斑", "小麦缺锰褐斑", "灰白或褐色小斑"),
  "que-liu": pair("que-liu", "整株偏黄，新叶也黄", "缺硫：新老叶一起黄，和缺氮相反", "缺硫新叶发黄", "新叶也黄，不是只黄老叶"),
  "que-tong": pair("que-tong", "叶尖发白卷曲、穗不实", "缺铜：叶尖发白，穗结实差", "小麦穗不实", "穗不实、叶尖卷"),
  "que-mu": pair("que-mu", "豆科叶片畸形、固氮差", "缺钼：豆叶畸形发黄", "大豆缺钼植株", "固氮差、叶片皱缩"),
  "huang-ye-jian-bie": pair("huang-ye-jian-bie", "黄叶四种对照", "老叶匀黄 / 新叶脉间黄 / 药害斑扭 / 涝害萎蔫", "黄叶叶位特写", "先分新叶还是老叶"),
  "lian-zuo": pair("lian-zuo", "连作棚点片死棵", "点片死棵，邻地轮作的却好", "连作根腐根结", "根发褐、根结或根腐"),
  "dashe-yanzhi": pair("dashe-yanzhi", "大棚膜下土面白霜", "棚膜下、滴灌口旁边白霜", "设施内盐斑", "能看出是大棚，不是露地"),
  "shao-gen": pair("shao-gen", "施肥沟里苗烧、根尖发黑", "能看出肥带，苗被烧", "烧根根尖褐黑", "根尖褐、种沟有肥粒"),
  "miao-qi-fei-hai": pair("miao-qi-fei-hai", "出苗不齐、小苗叶子焦", "苗期肥害：缺苗断垄、叶焦", "幼苗根尖发黑", "根尖黑，种肥贴种子"),
  "an-hai": pair("an-hai", "棚内叶缘焦像烟熏", "氨害：设施里叶缘焦", "氨气烧伤的嫩叶", "嫩叶边缘焦枯"),
  "lv-hai": pair("lv-hai", "马铃薯叶缘焦，氯害", "忌氯作物叶缘焦", "氯害焦边特写", "叶缘焦，问最近用了什么肥"),
  "di-guan-nong-du": pair("di-guan-nong-du", "滴头附近白霜烧圈", "滴灌口旁边白圈、烧根", "滴灌过浓伤苗", "午后萎蔫，滴口更重"),
  "wei-fu-shu-you-ji-fei": pair("wei-fu-shu-you-ji-fei", "未腐熟粪肥旁烧苗", "生粪堆边苗像被烫", "未腐熟有机肥发热", "粪还臭、苗焦"),
  "yao-hai": pair("yao-hai", "喷药后叶片扭曲斑驳", "药害：来得快，斑扭不规则", "药害心叶畸形", "心叶皱缩扭曲"),
  "lao-hai": pair("lao-hai", "田间积水、苗发黄萎蔫", "涝害：明水 + 白天萎蔫", "涝害根发黑", "根黑臭，土是湿的还蔫"),
  "fan-yan": pair("fan-yan", "浇后晒干地表一层白", "返盐：干了地表发白", "返盐白壳特写", "浇完又晒出来的盐霜"),
  "shi-hui-xing-tu": pair("shi-hui-xing-tu", "石灰性土壤表土发白", "石灰性土：养分不低叶子还黄", "石灰性土上的黄化植株", "铁被锁住的黄化"),
  "shi-gao-gai-jian": pair("shi-gao-gai-jian", "碱土撒石膏", "石膏是改碱的，不是所有白霜都能撒", "碱斑土柱", "pH 高、结构差的碱斑"),
  "sha-tu-lou-fei": pair("sha-tu-lou-fei", "沙土散漏，保不住肥", "沙质、一抓就散", "沙土地漏水", "雨后很快漏干"),
  "nian-tu-nan-geng": pair("nian-tu-nan-geng", "黏土干裂大块，难耕", "湿时黏锄、干时大块", "黏土地裂缝扯根", "龟裂大缝"),
  "li-di-ceng": pair("li-di-ceng", "剖面里一层致密犁底层，根拐弯", "下面硬盖，根水平走", "犁底层发亮硬盖特写", "20 厘米以下发亮的一层"),
  "hei-tu-tui-hua": pair("hei-tu-tui-hua", "黑土层变薄、心土露出、板硬", "不是又黑又肥的好土", "退化黑土风蚀", "耕层变浅、土色发灰发硬"),
  "jie-gan-huan-tian": pair("jie-gan-huan-tian", "秸秆还田后出苗黄弱", "还田后出苗差、苗黄", "还田秸秆覆盖的地", "粉碎压实不够也会出苗难"),
  "shi-hui-yong-liang": pair("shi-hui-yong-liang", "农用石灰撒在酸性土上", "石灰改酸要定量，不要撒苗上", "石灰粉堆在田间", "分两次、宁少勿多"),
  "xiu-shui-tian": pair("xiu-shui-tian", "锈色水面、黄僵稻苗", "亚铁毒，不是旱地玉米", "锈水油膜特写", "水面锈、根发黑"),
  "qian-yu-tian": pair("qian-yu-tian", "冷浸田灰蓝潜育层", "土冷、长期渍水、发青", "山垄冷浸稻田", "春季不发苗"),
  "shui-tian-huan-yuan": pair("shui-tian-huan-yuan", "深水田根黑不发新根", "长期深水、土发臭", "还原障碍黑根", "根黑臭，有硫化氢味"),
  "ce-tu-bao-gao": pair("ce-tu-bao-gao", "测土化验单 pH 有机质 EC", "先看 pH、有机质、盐分", "化验单养分表", "再看氮磷钾和微量元素"),
  "ce-tu-qu-yang": pair("ce-tu-qu-yang", "田间多点取样、土袋", "0～20 厘米，避开田边粪堆", "土钻取耕作层", "8～15 个点混合"),
  "gen-fu-jian-bie": pair("gen-fu-jian-bie", "黑腐根和白根对照", "点片死棵先看根", "根结线虫根", "根结、茎基缢缩"),
  "han-yan-jian-bie": pair("han-yan-jian-bie", "一边萎蔫无白霜，一边白霜加焦边", "旱了土干，咸了常有白霜", "抓一把干土对照", "先分土是干还是湿、白不白"),
  "cha-yuan-guo-suan": pair("cha-yuan-guo-suan", "茶园茶树行，不是粮田", "茶叶耐酸，不是越酸越好", "过酸茶园叶小", "过酸根差、叶小"),
  "ma-ling-shu-tu": pair("ma-ling-shu-tu", "马铃薯块茎疮痂", "皮上的疤，不是土面", "疮痂薯块特写", "偏碱偏干沙地更常见"),
  "sheng-wu-you-ji-fei": pair("sheng-wu-you-ji-fei", "腐熟堆肥", "先有有机质和通气，菌才住得下", "结构差的死土", "土不活时先改房改饭"),
  "guo-yuan-tu-rang": pair("guo-yuan-tu-rang", "果园树盘覆盖，不是大田", "树下活土、行间生草", "果园有机肥沟施", "肥要进根区"),
  "da-peng-lian-zuo-zong-he": pair("da-peng-lian-zuo-zong-he", "大棚连作：盐斑加病株", "盐、病、肥害熬在一口锅里", "棚内点片死棵加白霜", "越种死棵越多"),
  "wei-sheng-wu": pair("wei-sheng-wu", "结构差、板、无孔隙的死土", "不是最肥沃的团粒土", "发黏发臭的土块", "秸秆难腐烂、土臭"),
  "yang-fen-kang-kang": pair("yang-fen-kang-kang", "化验单某一项极高", "磷太高锌进不来", "拮抗示意：高磷植株小叶", "先把过高的停下来"),
  "hong-huang-rang-gai-suan": pair("hong-huang-rang-gai-suan", "红黄壤坡地玉米苗僵", "华南红土，不是麦苗全景", "红黄壤土色特写", "土色红黄，苗矮"),
  "lv-du-shang-gen": pair("lv-du-shang-gen", "酸土上根尖褐秃的植株", "根先伤，地上才僵", "洗出的褐秃根尖", "没有白尖，铝咬过"),
  "suan-yu-que-gai": pair("suan-yu-que-gai", "番茄脐腐贴在酸土田", "果脐黑腐，不是草莓", "脐腐特写", "只喷叶面钙不够"),
  "cha-yuan-shi-hui-jin-ji": pair("cha-yuan-shi-hui-jin-ji", "茶园行间，不是粮田", "茶树耐酸，不要按麦田撒石灰", "茶园土面特写", "不见麦苗"),
  "bin-hai-yan-tu": pair("bin-hai-yan-tu", "滨海盐土排水沟", "先排水，再谈培肥", "盐霜加沟渠", "能看出是海边不是大棚"),
  "di-biao-fu-yan": pair("di-biao-fu-yan", "地膜边白霜", "盐堆在膜边和滴口", "膜边盐圈特写", "中间湿球和膜边不一样"),
  "ji-ya-che-zhe": pair("ji-ya-che-zhe", "车辙里不出苗", "轮胎印是一条死土", "碾压土特写", "垄上有苗、辙里没有"),
  "hua-sheng-kong-jia": pair("hua-sheng-kong-jia", "花生田里的空荚", "果针吸钙，不是草莓", "空壳特写", "仁没灌满"),
  "qi-zi-huang-hua": pair("qi-zi-huang-hua", "柑橘新梢黄化", "先分缺铁、根腐、黄龙", "叶脉绿的新叶", "不是麦苗"),
  "pu-tao-shi-hui-tu-que-tie": pair("pu-tao-shi-hui-tu-que-tie", "石灰土上的葡萄黄叶", "土里有铁根吃不到", "葡萄新叶脉间黄", "钙质石子土"),
  "cao-mei-lian-zuo": pair("cao-mei-lian-zuo", "草莓棚点片死棵", "盐、线虫、黄萎挤在一起", "草莓根结或根腐", "能看出是草莓不是苹果"),
  "ping-guo-zai-zhi": pair("ping-guo-zai-zhi", "苹果老树坑再植", "挖了还是那坑土", "树坑心土特写", "不是草莓棚"),
  "gao-wen-men-peng": pair("gao-wen-men-peng", "高温闷棚后的土面", "能压菌也会伤结构", "闷过的干裂土", "不是露地麦田"),
  "leng-shui-guan-miao": pair("leng-shui-guan-miao", "进水口一条黄僵苗", "冷水灌苗，不是整田缺肥", "水口苗特写", "邻行更绿"),
  "shui-fei-yi-ti-hua-ec": pair("shui-fei-yi-ti-hua-ec", "滴灌口白圈腌根", "EC 超了就是在腌", "滴口烧圈特写", "不是蓝莓全集画面"),
  "que-xin-yu-lin": pair("que-xin-yu-lin", "玉米花白苗、节间短", "高磷常把锌挡住", "新叶条纹失绿", "不是下部匀黄的缺氮"),
  "wei-xian-shui-guan-gai": pair("wei-xian-shui-guan-gai", "微咸水灌进麦田，水边起白霜", "能浇但不能连浇", "地表盐晶特写", "水一干，盐就站在土面"),
  "yan-jian-di-xuan-zuo": pair("yan-jian-di-xuan-zuo", "盐斑垄上油菜还能出苗", "先活苗再求高产", "耐盐作物和旁边缺苗对照", "同块地，作物不同命运两样"),
  "xi-yan-pai-shui": pair("xi-yan-pai-shui", "田边排沟和盐斑对照", "有灌没排等于把盐赶上来", "土面白霜特写", "水有出路，盐才走得了"),
  "da-peng-huan-tu-xi-yan": pair("da-peng-huan-tu-xi-yan", "棚内滴口白霜、苗焦边", "先洗盐，别急着翻棚换土", "膜下盐晶特写", "新土加上旧习惯，盐还会回来"),
  "xuan-geng-bian-qian": pair("xuan-geng-bian-qian", "旋耕只翻浅层，下面还是硬盖", "年年旋，耕层越旋越浅", "根碰到硬层横走", "头发剪在表面，根过不去"),
  "shen-song-shi-ji": pair("shen-song-shi-ji", "深松铲把犁底层划开", "适墒、刚过硬盖就停", "土坑里发亮的硬盖特写", "不是越深越好，也不是年年松"),
  "tu-rang-tuan-ju-ti": pair("tu-rang-tuan-ju-ti", "手里搓得出团粒的活土", "好土像面包，粉土像面粉", "结构碎了的面土对照", "干了面、湿了浆，雨点一砸就散"),
  "ban-jie-yu-gen-xi": pair("ban-jie-yu-gen-xi", "根碰到硬盖拐弯横走", "板结和浅根互相喂", "浅旋后的硬层", "路不开，根不下去，土更板"),
  "fu-gai-gai-zhi-di": pair("fu-gai-gai-zhi-di", "地膜覆盖的玉米行", "覆盖是伞，不是镐", "秸秆盖住龟裂土", "挡雨挡蒸发，硬盖还是要松"),
  "lv-fei-fan-ya": pair("lv-fei-fan-ya", "绿肥被压进地里", "鲜草会发热、会抢氮", "秸秆覆盖对照", "花期翻、等几天、补一点氮"),
  "sheng-wu-tan": pair("sheng-wu-tan", "炭渣拌进耕层", "炭是架子，不是饭", "手里的生物炭特写", "一小把不能让地翻身"),
  "you-ji-fei-ru-he-xuan": pair("you-ji-fei-ru-he-xuan", "腐熟堆肥和生粪对照", "看腐熟、看盐、看碳氮比", "未腐熟和腐熟特写", "不烫手、不熏眼，颜色才对"),
  "jie-gan-bu-dan": pair("jie-gan-bu-dan", "还田后苗黄弱", "微生物先吃饭，苗会饿一阵", "秸秆旁黄苗特写", "补氮是还账，不是加倍追肥"),
  "hei-tu-you-ji-zhi-shou-hu": pair("hei-tu-you-ji-zhi-shou-hu", "东北黑土耕层", "黑的是肉，守住才有后劲", "黑土层和浅层对照", "再加氮也补不回变薄的黑土层"),
  "sha-tu-zeng-you-ji-zhi": pair("sha-tu-zeng-you-ji-zhi", "沙土里拌进堆肥", "少量多次，别一次堆山", "沙粒和有机肥拌匀特写", "筛子盛不住一座粪山"),
  "que-peng-hua-er-bu-shi": pair("que-peng-hua-er-bu-shi", "花开了却少荚少铃", "先查硼，也要查旱和盐", "茎空心开裂特写", "缺和毒只隔一层纸"),
  "ye-cai-xiao-xing-yuan-su": pair("ye-cai-xiao-xing-yuan-su", "叶菜新叶发黄、脉还绿", "喷叶是救急，不是改土", "菠菜脉间黄特写", "不要靠喷雾器过日子"),
  "yu-mi-miao-huang": pair("yu-mi-miao-huang", "玉米下部老叶匀黄", "缺氮、缺锌、药害、涝要分开", "叶脉间失绿特写", "一袋尿素盖不住四条路"),
  "gen-jie-xian-chong": pair("gen-jie-xian-chong", "棚里点片萎蔫的番茄", "根上长瘤，肥再多也不长", "根结线虫根瘤特写", "那些珠子不是根瘤菌"),
  "tu-chuan-ku-wei": pair("tu-chuan-ku-wei", "切开茎维管束发褐", "死棵先看管子，不是单纯旱", "茎髓特写", "点片死棵加褐管，再谈肥"),
  "qing-ku-bing-tu": pair("qing-ku-bing-tu", "热天番茄整株突然萎", "青枯来得快，闷棚不是万能", "茎内维管束对照", "切茎有时能挤出菌脓"),
  "han-lao-ji-zhuan": pair("han-lao-ji-zhuan", "刚涝过又干裂的田", "先伤根再黄叶", "龟裂土面特写", "旱涝急转，根来不及换气"),
  "di-xia-shui-wei-gao": pair("di-xia-shui-wei-gao", "土坑里很快渗出水", "水位高，根扎不深", "干裂但底下一层湿", "土面看着干，底下在憋"),
  "yu-hou-ban-jie-kai-lie": pair("yu-hou-ban-jie-kai-lie", "雨后玉米卡在硬壳里", "跑墒又卡苗", "土壳龟裂特写", "雨点砸实，太阳一晒就成锅盖"),
  "yan-jiang-qi-hou-tu": pair("yan-jiang-qi-hou-tu", "沿江稻田水冷苗黄", "潜育化比表面看起来更狠", "铲上一锹青灰色潜育土", "灰蓝土、锈斑，根不爱往下"),
  "ji-zhi-yu-tu-rang": pair("ji-zhi-yu-tu-rang", "基质袋栽和土栽在一个棚", "两套方子，不能抄", "椰糠和园土对照", "基质没有土壤的缓冲，EC 更敏感"),
  "tu-rang-xiao-du-bian-jie": pair("tu-rang-xiao-du-bian-jie", "闷棚薄膜盖着土面", "能压菌，消完要养", "薄膜下的土面特写", "消完接着连作，病菌会回来"),
  "jian-yi-ph-ec": pair("jian-yi-ph-ec", "地头用试纸和电导仪", "先会用这两样，再谈化验单", "试纸浸土浆特写", "数字是区间，不是判决书"),
  "shi-fei-tiao-tu-rang": pair("shi-fei-tiao-tu-rang", "黄叶和化验单对照着看", "看叶片能猜，不能代替测土", "手里叶子和报告", "叶色是线索，化验才是账本"),
  "nan-fang-shui-tian-yang-fen": pair("nan-fang-shui-tian-yang-fen", "南方水田苗黄水冷", "还原层把养分锁住了", "水稻叶面褐斑特写", "长期深水，铁锰起来、养分下去"),
  "sheng-li-suan-xing-fei": pair("sheng-li-suan-xing-fei", "生理酸性肥袋子", "铵态氮连年用，土会越用越酸", "肥袋和酸化苗对照", "不是缺肥，是房间先酸了"),
  "shui-dao-jiang-miao": pair("shui-dao-jiang-miao", "水稻僵苗不发棵", "水冷、根黑、邻丘却绿", "僵苗根特写", "先看根和水，再谈肥"),
  "su-da-yan-jian": pair("su-da-yan-jian", "苏打碱斑土面发白发涩", "碱和盐不是一回事", "碱斑结构差特写", "石膏是改碱的，不是见白就撒"),
  "suan-tu-shi-lin": pair("suan-tu-shi-lin", "酸土上发紫发僵的玉米苗", "磷被锁住，苗紫矮", "紫苗和根对照", "先改酸，再谈补磷"),
};

export function photosFor(slug: string): ArticlePhoto[] {
  if (COVER[slug]) return COVER[slug]!;
  return pair(slug, "田间对照", "田间尺度，对照自家地", "诊断特写", "把本题和近亲题分开看");
}
