import type { Article } from "./types";
import { biliSearch, makeArticle } from "./helpers";

export const SET_A: Article[] = [
  makeArticle({
    slug: "suan-hua",
    title: "土壤酸化：土变酸了，苗发僵不长",
    subtitle: "土发酸、水发锈，庄稼根系发黄发褐",
    summary: "南方水田、茶园、果园和高氮施肥地块最常见。土越来越酸，磷钙镁被锁住，铝离子伤根，苗发僵。",
    crops: ["水稻", "茶叶", "果树", "花生", "蔬菜", "玉米"],
    problems: ["酸化"],
    regions: ["华南", "长江中下游", "西南"],
    seasons: ["全年"],
    tags: ["酸化", "pH", "石灰", "铝毒"],
    coverCrop: null,
    coverType: "plant",
    phenomenon: {
      appearance: "秧苗、菜苗矮小发僵，新根少、根尖发褐；老叶发黄，严重时叶缘焦。浇水后有时冒锈水。果树新梢短。茶叶虽耐酸，过酸同样伤根。",
      conditions: "多雨湿润红黄壤、长期单施铵态氮和生理酸性肥、不施有机肥。",
      commonCrops: "水稻、茶叶、柑橘、花生、蔬菜、玉米。茶叶喜欢偏酸，但不是越酸越好。",
    },
    confuseWith: [
      { other: "缺氮黄叶", difference: "缺氮是下部老叶均匀黄、新叶还绿；酸化是根先伤、整株发僵。", lookAt: "拔苗看根尖是不是褐、少。" },
      { other: "冷害发僵", difference: "低温回暖会缓；酸化回暖也不长，要测 pH。", lookAt: "测 0～20 厘米 pH，并问是否连年高氮。" },
    ],
    causes: {
      natural: ["红黄壤盐基少，雨水把钙镁冲走。", "母质含铝高，酸了以后铝溶出来咬根。"],
      human: ["长期只施尿素、氯化铵、硫酸铵。", "秸秆不还田，缓冲能力变差。"],
      plainExplain: "pH 越小越酸。多数庄稼喜欢 6.0～7.5。土太酸，钙镁磷抓不住，铝却咬根。不是肥不够，是根吃不进去。茶叶适宜大约 4.5～6.0，低于 4.0 也伤。",
    },
    solutions: {
      steps: [
        "先测土。低于 5.5 才优先改酸；5.5～6.0 先观察。茶叶另算。",
        "水田、黏土常用农用石灰；旱地可用白云石粉。生石灰不要直接撒苗上。",
        "用量按测土和质地，宁少勿多：农用石灰常见每亩 50～150 公斤，分两次。沙土少一点，黏土可略多。",
        "秋收后到春播前 15 天撒匀旋进 15～20 厘米。与铵态氮、粪肥隔 7～10 天。",
        "配合腐熟有机肥，暂停生理酸性肥。",
      ],
      videos: [biliSearch("如何调理土壤酸化问题", "BV1jT6TYXEjx")],
    },
    dosages: [
      { item: "农用石灰", range: "每亩 50～150 公斤，分两次", note: "pH<5.5 才优先；按测土，宁少勿多" },
      { item: "白云石粉", range: "与石灰相近，带镁", note: "旱地酸性土；先小面积" },
      { item: "腐熟有机肥", range: "每亩 1～2 吨量级", note: "改缓冲，按当地" },
    ],
    prevention: ["有机肥与化肥搭配。", "避免连年高氮。", "定期测 pH。"],
    indicators: [
      { name: "pH", meaning: "酸碱", typical: "多数作物 6.0～7.5，茶叶例外" },
      { name: "交换性铝", meaning: "酸了咬根的铝", typical: "pH 低于 5.5 容易升高" },
    ],
    relatedSlugs: ["shi-hui-yong-liang", "que-lin", "cha-yuan-guo-suan"],
    featured: true,
    hot: true,
  }),
  makeArticle({
    slug: "yan-jian",
    title: "盐碱地：土面发白，苗出不来或焦边",
    subtitle: "白霜、结皮、出苗不齐，是盐在作怪",
    summary: "北方干旱区和滨海地带常见。盐把根周围的水抢走，苗像旱死，叶边焦。",
    crops: ["小麦", "玉米", "棉花"],
    problems: ["盐碱"],
    regions: ["华北", "西北", "黄淮海"],
    seasons: ["春季", "冬季"],
    tags: ["盐碱", "白霜", "EC", "洗盐"],
    coverCrop: null,
    coverType: "soil",
    phenomenon: {
      appearance: "土面白粉或白霜，干了结皮；出苗慢、缺苗断垄；叶缘焦枯，像被开水烫过。",
      conditions: "干旱、蒸发大、地下水位高、大水漫灌后又旱。春季最明显，冬灌管理不当也会返盐。",
      commonCrops: "棉花、小麦、玉米。有淡水可用水稻压盐。",
    },
    confuseWith: [
      { other: "干旱萎蔫", difference: "旱了浇水能缓；咸了浇小水有时更蔫。白霜是盐的记号。", lookAt: "看土面白霜，浇水后是缓还是更蔫。" },
      { other: "缺钾焦边", difference: "缺钾土面不一定白；盐害常伴出苗差。", lookAt: "对照土面和出苗。" },
    ],
    causes: {
      natural: ["雨水少，盐淋不下去。", "地下水咸，盐被抽到地表。"],
      human: ["只灌不排。", "高盐肥一把撒。"],
      plainExplain: "根喝水靠浓度差。土太咸，水被盐抢走。盐害看 EC/全盐，碱害看 pH 和钠。",
    },
    solutions: {
      steps: [
        "先测 EC/全盐和 pH，分清盐害还是碱害。",
        "有排水才洗盐。没有沟的大水只会把盐推到别处。",
        "春季返盐前覆盖、中耕，减少蒸发。冬灌要有出路。",
        "种肥离种子远一点，分次施，不要在盐斑上猛施肥当缺肥。",
        "苏打碱土才考虑石膏，不是所有白霜都能撒。",
      ],
      videos: [biliSearch("盐碱地改良")],
    },
    dosages: [
      { item: "洗盐", range: "有淡水和排水才灌排", note: "没有沟不要大水漫灌" },
      { item: "覆盖", range: "秸秆或地膜", note: "减少蒸发，盐少往上爬" },
      { item: "农用石膏", range: "仅碱化土按测土", note: "不是所有白霜都能撒" },
    ],
    prevention: ["灌排配套。", "薄肥勤施。", "春季返盐前覆盖。"],
    indicators: [
      { name: "EC / 全盐", meaning: "咸度", typical: "苗期更敏感" },
      { name: "pH", meaning: "分清盐还是碱", typical: "碱害还要看钠" },
    ],
    relatedSlugs: ["fan-yan", "shi-gao-gai-jian", "han-yan-jian-bie"],
    featured: true,
    hot: true,
  }),
  makeArticle({
    slug: "ban-jie",
    title: "土壤板结：锄不动，根翻不上来",
    subtitle: "硬土块、雨后积水、苗戴帽出土",
    summary: "机耕层变浅、有机质低。出苗费劲，根系浅，既怕旱又怕涝。",
    crops: ["水稻", "小麦", "玉米", "蔬菜"],
    problems: ["板结"],
    regions: ["全国"],
    seasons: ["全年"],
    tags: ["板结", "犁底层", "深松"],
    coverCrop: null,
    coverType: "soil",
    phenomenon: {
      appearance: "土表面结壳，锄头刨下去是硬块；雨后积水，干后裂缝；苗出土戴帽，根横向走。",
      conditions: "黏粒多、有机质低、常年浅旋耕、雨后碾压。",
      commonCrops: "小麦、玉米、水稻、蔬菜，黏土地更重。",
    },
    confuseWith: [
      { other: "干旱", difference: "旱是没水；板结是有水也进不去。", lookAt: "雨后是否积水、干后是否结壳。" },
      { other: "犁底层", difference: "整层硬是板结，下面一层硬盖是犁底层。", lookAt: "刨到 20 厘米以下看有没有发亮硬盖。" },
    ],
    causes: {
      natural: ["黏粒多、有机质低，团粒散了就黏死。"],
      human: ["常年浅旋耕、雨后进地碾压。", "秸秆不还田。"],
      plainExplain: "好土像发好的馒头，板结土像实心砖。水和根都过不去。",
    },
    solutions: {
      steps: [
        "雨后积水先排水，不要泥里开拖拉机。",
        "隔年深松 25～40 厘米打破硬盖，不要年年深翻生土。",
        "同时补腐熟有机肥，让松过的土不再迅速压实。",
        "黏土适墒再耕：手握成团落地能散。",
        "低洼田先把水排走，再谈深松。",
      ],
      videos: [biliSearch("土壤板结怎么处理")],
    },
    dosages: [
      { item: "深松深度", range: "一般 25～40 厘米", note: "隔年，按剖面" },
      { item: "腐熟有机肥", range: "每亩 1～2 吨量级", note: "松完要有肉" },
    ],
    prevention: ["适墒耕作。", "有机肥和还田。", "避免雨后碾压。"],
    indicators: [
      { name: "容重", meaning: "土紧不紧", typical: "耕层过大说明板结" },
      { name: "有机质", meaning: "团粒的家底", typical: "低了更容易板" },
    ],
    relatedSlugs: ["li-di-ceng", "you-ji-zhi", "nian-tu-nan-geng"],
    hot: true,
  }),
  makeArticle({
    slug: "you-ji-zhi",
    title: "有机质下降：土越种越“馋”，越种越瘦",
    subtitle: "土色发浅、不保水不保肥",
    summary: "化肥能当季增产，但土里的家底是有机质。家底薄了，肥效差、病害多。",
    crops: ["全国"],
    problems: ["有机质低"],
    regions: ["全国"],
    seasons: ["全年"],
    tags: ["有机质", "秸秆还田", "保肥"],
    coverCrop: null,
    coverType: "soil",
    phenomenon: {
      appearance: "土色浅、干、散；浇水很快漏或很快板；同样施肥不如邻地；病虫害偏多。",
      conditions: "秸秆拿走、不施农家肥、连年翻耕、沙土本身保不住。",
      commonCrops: "所有作物。设施蔬菜和粮田都普遍。",
    },
    confuseWith: [
      { other: "单纯缺氮", difference: "缺氮当季追肥能绿；有机质低是年年都馋、肥留不住。", lookAt: "看土色和连年肥效，不要只看这一季叶子。" },
      { other: "沙土漏肥", difference: "沙土是质地问题，有机质低在黏土里也会发生。", lookAt: "搓土：沙土粒感明显；瘦黏土又黏又没油润。" },
    ],
    causes: {
      natural: ["高温高湿分解快。", "沙土孔隙大，有机质留不住。"],
      human: ["秸秆焚烧或拿走。", "长期单施化肥、过度翻耕。"],
      plainExplain: "有机质是土的“肉”。没肉的土像空沙袋，肥灌进去留不住。",
    },
    solutions: {
      steps: [
        "秸秆粉碎还田，配合适量氮，避免抢氮黄苗。",
        "每年施腐熟有机肥，按当地农技站用量。",
        "种植绿肥、少耕。",
        "不要指望一个月养成黑土，连续三年可见效。",
      ],
      videos: [biliSearch("土壤有机质怎么提高")],
    },
    dosages: [
      { item: "腐熟有机肥", range: "每亩 1～2 吨量级", note: "按当地和来源，必须腐熟" },
      { item: "秸秆还田补氮", range: "每亩尿素几公斤量级", note: "按秸秆量和农技站，防止抢氮" },
    ],
    prevention: ["拿走多少还回多少。", "有机无机配合。"],
    indicators: [{ name: "有机质", meaning: "家底", typical: "北方旱地大约 12～20 g/kg 为中等偏好，按当地标准读报告" }],
    relatedSlugs: ["jie-gan-huan-tian", "sheng-wu-you-ji-fei", "wei-sheng-wu"],
    hot: true,
  }),
  makeArticle({
    slug: "que-dan",
    title: "缺氮：下部老叶先黄，植株瘦高不壮",
    subtitle: "黄的是老叶子，不是新叶子",
    summary: "氮是长叶子的养分。不够时，植株把老叶里的氮抽去养新叶，所以底下先黄。",
    crops: ["水稻", "小麦", "玉米", "蔬菜"],
    problems: ["缺素"],
    regions: ["全国"],
    seasons: ["春季", "夏季"],
    tags: ["缺氮", "黄叶", "尿素"],
    coverCrop: "小麦",
    coverType: "plant",
    phenomenon: {
      appearance: "叶色淡黄，从下部老叶开始均匀褪绿（不像缺铁那样叶脉还绿）；植株瘦、分蘖少；穗小。涝害、板结也会黄，要看根。",
      conditions: "沙土漏肥、降雨大、秸秆还田初期抢氮、底肥不足。",
      commonCrops: "玉米、小麦、水稻、叶菜。",
    },
    confuseWith: [
      { other: "缺铁", difference: "缺铁黄新叶、叶脉绿；缺氮黄老叶、整叶较匀。", lookAt: "先分新叶还是老叶。" },
      { other: "涝害黄叶", difference: "涝害常白天萎蔫、根发黑发臭。", lookAt: "看根和是否积水。" },
    ],
    causes: {
      natural: ["沙土、降雨淋洗硝态氮。", "冷湿土壤矿化慢。"],
      human: ["底肥不够或一次施太多后期脱肥。", "秸秆还田不补氮。"],
      plainExplain: "氮像庄稼的饭量。不够就先饿老叶子。叶子发黄不一定是缺氮：根坏了、水淹了也会黄。",
    },
    solutions: {
      steps: [
        "确认根系正常后，追施尿素或高氮肥，少量多次。",
        "玉米拔节、叶菜生长期是需氮高峰，按生育期追。",
        "不要一次猛冲，避免旺长和烧叶。",
        "配合有机肥，减少后期脱肥。",
      ],
      videos: [biliSearch("玉米缺氮症状")],
    },
    dosages: [
      { item: "尿素追肥", range: "每亩常见 5～15 公斤量级，分次", note: "按测土和苗情，宁少勿多；先小面积" },
      { item: "叶面补氮", range: "按商品说明稀释", note: "只救急，不能替代土施" },
    ],
    prevention: ["测土配方，分次施肥。", "秸秆还田补适量氮。"],
    indicators: [{ name: "碱解氮 / 硝态氮", meaning: "当季能用的氮", typical: "过低需追，过高易旺长倒伏" }],
    relatedSlugs: ["huang-ye-jian-bie", "que-liu", "jie-gan-huan-tian"],
    hot: true,
  }),
  makeArticle({
    slug: "que-jia",
    title: "缺钾：叶子从边缘焦枯，像被火烧",
    subtitle: "老叶边缘先焦，果实不甜不耐贮",
    summary: "钾管水分和品质。不够时叶缘焦枯、茎秆弱易倒伏，瓜果不甜。",
    crops: ["水稻", "玉米", "蔬菜", "果树"],
    problems: ["缺素"],
    regions: ["全国"],
    seasons: ["夏季", "秋季"],
    tags: ["缺钾", "叶缘焦枯"],
    coverCrop: null,
    coverType: "plant",
    phenomenon: {
      appearance: "老叶叶缘发黄焦枯向内发展；茎秆细弱易倒；棉铃、果穗不充实，口感差。",
      conditions: "沙土、高产田带走钾多、只施氮磷、南方淋溶强。",
      commonCrops: "棉花、玉米、水稻、香蕉、马铃薯、番茄。",
    },
    confuseWith: [
      { other: "盐害焦边", difference: "盐害常有土面白霜、出苗差；缺钾土面不一定白。", lookAt: "先看土面有没有白霜。" },
      { other: "药害焦斑", difference: "药害来得快、斑驳不规则；缺钾从老叶缘慢慢焦。", lookAt: "问最近几天有没有喷药。" },
    ],
    causes: {
      natural: ["沙土保钾差。", "降雨淋洗。"],
      human: ["高产拿走秸秆。", "偏施氮肥。"],
      plainExplain: "钾不像氮立刻让叶子浓绿，它更像体质。缺了叶边先烧，不抗旱、不抗倒。",
    },
    solutions: {
      steps: [
        "先排除盐害和药害，再考虑补钾。",
        "土施硫酸钾或氯化钾，忌氯作物只用硫酸钾。",
        "叶面磷酸二氢钾救急，先小面积，避开中午。",
        "秸秆能还就还，高产田把钾当常规底肥。",
      ],
      videos: [biliSearch("作物缺钾症状")],
    },
    dosages: [
      { item: "土施钾肥", range: "每亩常见 5～15 公斤量级", note: "忌氯作物用硫酸钾；按测土" },
      { item: "叶面磷酸二氢钾", range: "常见 0.2%～0.3% 量级", note: "先小面积，只救急" },
    ],
    prevention: ["秸秆还田还钾。", "氮磷钾搭配。"],
    indicators: [{ name: "速效钾", meaning: "当季能用的钾", typical: "沙土、高产田易低；焦边还要排除盐害" }],
    relatedSlugs: ["yan-jian", "lv-hai", "huang-ye-jian-bie"],
    hot: true,
  }),
];
