import type { UniquePatch } from "./unique-types";

export const UNIQUE_B: Record<string, UniquePatch> = {
  "que-meng": {
    uniqueAngle: "新叶褐斑，锰不搬家",
    subtitle: "新叶脉间黄还带褐点，别当成缺铁",
    summary: "锰几乎不往老叶撤。新叶脉间失绿、散生褐斑。过酸沙土和刚过量石灰都可能。",
    fieldCheck: "掐顶端新叶：脉间黄带褐色小点，老叶还绿。问是不是刚改过酸。",
    dontDo: ["新叶黄就喷螯合铁", "过酸田不测锰土施一把", "褐斑当病害连打药"],
    whenToTest: "新叶褐斑时测有效锰，并看 pH。",
    prevention: ["改酸要小幅，锰才稳。", "叶面锰按下限先小面积。", "不要一年过酸一年过碱。"],
    phenomenon: { appearance: "新叶脉间黄、褐斑，老叶相对好。", conditions: "强酸沙土、过湿、刚过量石灰。", commonCrops: "小麦、大豆、蔬菜。" },
    confuse: [
      { lookalike: "缺铁", difference: "缺铁脉绿肉黄、斑点少；缺锰常带褐斑。", photoHint: "新叶特写看有没有褐点。" },
      { lookalike: "药害斑", difference: "药害喷后1～3天、沿雾滴；缺锰慢慢铺。", photoHint: "问喷药日。" },
    ],
    causes: { plainExplain: "锰是新叶的油漆工，油漆桶搬不走，新叶先花再冒褐点。", natural: ["酸沙土锰易淋。", "过湿还原改形态。"], human: ["石灰一次改过劲。", "新叶黄一律喷铁。"] },
    dosage: [{ name: "叶面硫酸锰（确认缺锰）", range: "按包装下限，新叶期分两次，先小面积", note: "土施看测土" }],
    relatedSlugs: ["que-tie", "suan-hua", "huang-ye-jian-bie"],
    steps: ["看新叶褐斑不是老叶匀黄。", "测有效锰和 pH。", "叶面按下限先小面积。", "过酸只小幅改。", "沿雾滴的斑先当药害。"],
    indicators: [{ name: "有效锰", meaning: "新叶褐斑的数字", typical: "过酸沙土常低" }, { name: "pH", meaning: "改过了锰会被钉", typical: "刚改酸更要看" }],
  },
  "que-liu": {
    uniqueAngle: "新叶也黄，和缺氮叶位相反",
    subtitle: "心叶跟着黄，不是下部先脱色",
    summary: "硫不往老叶撤。新叶也黄、叶脉也淡。看起来像缺氮，缺氮却是老叶先黄、心叶还绿。",
    fieldCheck: "把心叶和老叶摆一起：心叶也黄更像硫；只有老叶匀黄先当氮。",
    dontDo: ["整株黄就加倍尿素", "沙土年年只上无硫高氮", "硫黄糊在苗上"],
    whenToTest: "新叶也黄、沙土或有机质低时测有效硫。",
    prevention: ["复合肥偶尔选含硫的。", "有机质垫上硫才留得住。", "沙土少量多次。"],
    phenomenon: { appearance: "整株发黄，新老叶一起淡，叶脉也褪。", conditions: "沙土、高雨、长期无硫肥。", commonCrops: "油菜、玉米、小麦。" },
    confuse: [
      { lookalike: "缺氮", difference: "缺氮老叶先黄心叶还绿；缺硫心叶一起黄。", photoHint: "摘心叶比颜色。" },
      { lookalike: "缺铁", difference: "缺铁脉还绿；缺硫连脉也淡。", photoHint: "看叶脉。" },
    ],
    causes: { plainExplain: "氮是家里存粮，缺了先吃老库存；硫是随身口袋，口袋空了新叶也黄。", natural: ["沙土淋得快。", "有机质薄硫库小。"], human: ["年年只上尿素和磷铵。", "见黄就追氮。"] },
    dosage: [{ name: "含硫肥（确认缺硫）", range: "随基肥或追肥带硫，按测土，沙土分次", note: "不要硫黄糊苗" }],
    relatedSlugs: ["que-dan", "huang-ye-jian-bie", "sha-tu-lou-fei"],
    steps: ["对照心叶和老叶。", "测有效硫。", "氮先不要加倍。", "含硫肥按测土补。", "有机质一起垫。"],
    indicators: [{ name: "有效硫", meaning: "新叶也黄时看它", typical: "沙土常低" }, { name: "有机质", meaning: "硫的仓库", typical: "低了留不住" }],
  },
  "que-tong": {
    uniqueAngle: "叶尖发白、穗不实，铜不搬家",
    subtitle: "秕穗加白尖，不是单纯干旱",
    summary: "铜不搬家。叶尖发白变窄、穗结实差。高有机质泥炭土会把铜扣住。",
    fieldCheck: "抽穗后看秕粒和叶尖白卷。问土是很黑很黏还是很酸的沙。",
    dontDo: ["空穗只浇水当旱", "高有机质土不测铜土施一把", "叶尖白当药害连打"],
    whenToTest: "秕穗、叶尖白卷时测有效铜，并看有机质。",
    prevention: ["泥炭土更要盯铜。", "叶面铜按下限。", "铜制剂杀菌不要叠成过量。"],
    phenomenon: { appearance: "叶尖发白卷、穗空。", conditions: "高有机质泥炭土、过酸沙土。", commonCrops: "小麦、水稻。" },
    confuse: [
      { lookalike: "干旱秕穗", difference: "旱了土干中午蔫；缺铜土不一定干。", photoHint: "抓一把土干不干。" },
      { lookalike: "药害白尖", difference: "药害有喷药日、来得快。", photoHint: "问最近喷没喷。" },
    ],
    causes: { plainExplain: "铜是灌浆的焊条，焊条被泥炭吸住，穗看起来结了里面是空的。", natural: ["高有机质络合铜。", "酸沙土铜易淋。"], human: ["只看空穗浇水。", "铜剂杀菌喷过头。"] },
    dosage: [{ name: "叶面铜（确认缺铜）", range: "按包装下限一次，先小面积", note: "高有机质土必须化验" }],
    relatedSlugs: ["que-dan", "yao-hai", "huang-ye-jian-bie"],
    steps: ["看白尖和秕穗，排除单纯干旱。", "测有效铜。", "叶面按下限。", "正在用铜杀菌的先停。", "不要盲目土施。"],
    indicators: [{ name: "有效铜", meaning: "秕穗加白尖", typical: "泥炭土常低" }, { name: "有机质", meaning: "太高会扣铜", typical: "和铜一起读" }],
  },
  "que-mu": {
    uniqueAngle: "豆科固氮差，钼是固氮酶螺丝",
    subtitle: "根瘤不红、叶子畸形，先别猛尿素",
    summary: "豆科缺钼，固氮先垮。酸土钼被铁铝钉住。先改酸，根瘤才会干活。",
    fieldCheck: "挖大豆或花生根：瘤小、切开不鲜红。叶子皱。测 pH。",
    dontDo: ["豆科发黄猛尿素", "过酸不改只喷钼", "把根瘤菌剂当可以替代改土"],
    whenToTest: "豆科固氮差、叶畸形时测有效钼和 pH。",
    prevention: ["酸性豆田先把 pH 抬到适宜。", "钼按极低量。", "土太酸菌也住不稳。"],
    phenomenon: { appearance: "豆叶畸形脉间黄，根瘤切开不红。", conditions: "酸性红黄壤豆田。", commonCrops: "大豆、花生。" },
    confuse: [
      { lookalike: "缺氮", difference: "缺氮老叶匀黄、瘤可能还红；缺钼瘤先没光。", photoHint: "切开根瘤看颜色。" },
      { lookalike: "铝毒", difference: "铝毒根尖褐秃；缺钼根可以在、瘤不干活。", photoHint: "根尖和根瘤分开关。" },
    ],
    causes: { plainExplain: "钼是固氮酶上那颗小螺丝，螺丝锈在酸土里，根瘤空转。", natural: ["酸土钼被铁铝固定。"], human: ["豆科发黄只追氮。"] },
    dosage: [{ name: "钼酸铵叶面（确认缺钼）", range: "按包装极低量，苗期到初花一次，先小面积", note: "过酸先改酸" }],
    relatedSlugs: ["suan-hua", "que-dan", "lv-du-shang-gen"],
    steps: ["挖根看瘤颜色。", "测 pH 和钼。", "过酸先少量改酸。", "钼极低量叶面。", "不要用尿素把固氮懒掉。"],
    indicators: [{ name: "有效钼", meaning: "固氮螺丝", typical: "酸土常低" }, { name: "pH", meaning: "酸了钼被钉", typical: "豆田过酸先改" }],
  },
  "huang-ye-jian-bie": {
    uniqueAngle: "黄叶总鉴别，不给任何一种元素的完整施肥方案",
    subtitle: "先分叶位、根和土面，再谈缺哪一种",
    summary: "黄叶有四条路：缺素、涝害、药害、病害。这篇只教怎么分，不给氮磷钾锌的用量。",
    fieldCheck: "到地里先看三样：叶位（新叶还是老叶）、根（白、褐还是臭）、土面（白霜、积水还是干裂）。三样对不上，不要急着下肥。",
    dontDo: ["黄了就按缺氮追尿素", "不看叶位把四种黄混成一种", "这篇当施肥处方用"],
    whenToTest: "分不清叶位或土面有白霜、积水时，测 pH、EC、有机质。",
    prevention: ["拍照留整株、特写、土面三张。", "先排除涝和药，再谈缺素。", "一种元素的办法去该元素那篇。"],
    phenomenon: { appearance: "地里一片黄，但黄的位置、快慢、土面各不相同。", conditions: "任何作物、任何季节，只要有人看见黄。", commonCrops: "所有大田和棚室。" },
    confuse: [
      { lookalike: "一种缺素处方", difference: "总鉴别不分处方；每种元素另有专篇。", photoHint: "本页没有用量公斤表。" },
      { lookalike: "病害黄化", difference: "病害常点片、有病斑或虫；缺素常成片按叶位。", photoHint: "点片还是整垄，有没有病斑。" },
    ],
    causes: { plainExplain: "黄叶是路口，不是地名。先看你从哪条路走来，再决定进哪一扇门。", natural: ["涝、旱、盐都会黄。"], human: ["喷药、施肥、连作也会黄。"] },
    dosage: [{ name: "这篇不下肥", range: "不给任何元素的公斤数", note: "分清后再进专篇" }],
    relatedSlugs: ["que-dan", "que-tie", "yao-hai"],
    steps: ["看叶位：老叶匀黄偏氮，新叶脉间黄偏铁。", "看根：臭黑先涝或病。", "看土面：白霜偏盐，明水偏涝。", "喷后1～3天斑扭偏药害。", "仍不清就测土，不要混打微肥。"],
    indicators: [{ name: "叶位", meaning: "移动性的第一刀", typical: "老叶/新叶" }, { name: "土面", meaning: "盐涝旱的记号", typical: "白霜、积水、干裂" }],
  },
};
