import type { UniquePatch } from "./unique-types";

export const UNIQUE_MORE: Record<string, UniquePatch> = {
  "shi-hui-yong-liang": {
    uniqueAngle: "农用石灰、白云石、生石灰怎么选，怎么隔开铵态氮",
    subtitle: "改酸的药要认包装，不要跟尿素同一天撒",
    summary: "农用石灰改酸，白云石带镁，生石灰劲猛伤苗。用量按质地和 pH，沙土少、黏土略多，分两次。铵态氮隔 7～10 天。",
    fieldCheck: "看包装写的是农用石灰、白云石还是生石灰。量一次只撒一半，跟尿素错开一周。",
    dontDo: ["生石灰直接撒苗上", "石灰和尿素、鲜粪同一天混", "沙土按黏土上限一次铺满", "不看包装把建筑石灰当农用石灰"],
    whenToTest: "改酸前测 pH 和质地；撒后下一季再测。",
    prevention: ["改酸用农用石灰或白云石，生石灰留给空地。", "和铵态氮错开。", "分两次，宁少勿多。"],
    phenomenon: { appearance: "地里已经决定要改酸，问题变成用哪种灰、撒多少、何时撒。", conditions: "pH 已经测过、低于目标。", commonCrops: "粮田旱地。茶园去禁忌那篇。" },
    confuse: [
      { lookalike: "建筑石灰、窑灰", difference: "农用石灰有氧化钙含量；建筑灰杂质多、易烧苗。", photoHint: "看包装成分，不要看颜色。"},
      { lookalike: "石膏", difference: "石膏改碱不改酸。白粉不是同一种药。", photoHint: "先看 pH 是低还是高。" },
    ],
    causes: { plainExplain: "石灰是中和酸的药片，药片种类不同、饭前饭后不同。跟尿素同桌会抢氮。", natural: ["质地决定缓冲，沙土一点就过。"], human: ["图省事一次撒到头。", "跟氮肥混在一个筐。" ] },
    dosage: [{ name: "农用石灰（粮田 pH＜5.5）", range: "常见每亩 50～150 公斤，分两次，沙土按下限、黏土略多", note: "用量按测土和当地农技站，宁少勿多。" }, { name: "白云石粉", range: "与石灰相近，带镁", note: "旱地缺镁时优先" }],
    relatedSlugs: ["suan-hua", "hong-huang-rang-gai-suan", "cha-yuan-shi-hui-jin-ji"],
    steps: ["确认测过 pH。", "认包装：农用石灰或白云石，生石灰不往苗上撒。", "按质地取区间下限，分两次。", "与铵态氮隔 7～10 天。", "下一季再测，过了目标就停。"],
    indicators: [{ name: "pH", meaning: "要不要改、改没改过", typical: "粮田目标大约 6 左右" }, { name: "质地", meaning: "沙少黏多", typical: "手测能感觉" }],
  },
  "cha-yuan-guo-suan": {
    uniqueAngle: "茶树耐酸不等于越酸越好",
    subtitle: "茶叶喜欢偏酸，不是喜欢喝醋",
    summary: "茶树适宜大约 pH 4.5～6.0。低于 4.0 根一样伤、叶变小。不要按粮田改到中性，也不要放任过酸。",
    fieldCheck: "茶园单独取 0～20 厘米测 pH。叶小、根褐、低于 4.0 才考虑极少量改。",
    dontDo: ["按粮田目标改到 6.5～7", "过酸不测就当缺肥", "茶行里撒生石灰"],
    whenToTest: "茶芽瘦、根差时测 pH，茶园不要和粮田混样。",
    prevention: ["茶园单独建档案，不要和稻田一个石灰账。", "有机质比石灰更常用。", "改完再测，停在 4.5～6.0。"],
    phenomenon: { appearance: "茶树还活着但叶小、新梢短、根色差。", conditions: "多年高氮、多雨红黄壤茶园。", commonCrops: "茶叶。不见麦苗。" },
    confuse: [
      { lookalike: "粮田酸化", difference: "粮田目标更高；茶园改到中性会伤树。", photoHint: "看是茶行还是麦垄。" },
      { lookalike: "缺氮", difference: "缺氮老叶黄；过酸是根差叶小。", photoHint: "挖根，不要只看叶色。" },
    ],
    causes: { plainExplain: "茶树能喝酸，不等于拿醋当水。杯子太酸，根一样皱。", natural: ["红黄壤本底酸。"], human: ["高氮、不还有机、按邻居稻田撒石灰。" ] },
    dosage: [{ name: "茶园改酸（仅 pH＜4.0 时）", range: "农用石灰按测土极低量、分次，目标停在 4.5～6.0", note: "绝不能按粮田 50～150 公斤照抄" }],
    relatedSlugs: ["cha-yuan-shi-hui-jin-ji", "suan-hua", "shi-hui-yong-liang"],
    steps: ["茶园单独取样测 pH。", "4.5～6.0 先养有机质，不要改。", "低于 4.0 才极少量农用石灰。", "不用生石灰。", "改完停在适宜区间。"],
    indicators: [{ name: "pH", meaning: "茶园自己的尺子", typical: "大约 4.5～6.0" }],
  },
  "cha-yuan-shi-hui-jin-ji": {
    uniqueAngle: "茶园绝不能按粮田石灰账",
    subtitle: "粮田那套公斤数，在茶行里是伤树",
    summary: "茶园石灰是禁忌操作：种类、用量、时期都和粮田不同。拿不准就先不撒。",
    fieldCheck: "看邻地是不是稻田刚撒过灰。茶行里有灰堆，先停。测茶园自己的 pH。",
    dontDo: ["把稻田剩余石灰倒进茶行", "生石灰消毒当改酸", "改到中性还继续加"],
    whenToTest: "任何人建议茶园撒石灰时，先看本园 pH。",
    prevention: ["茶园改酸只走过酸那篇，不走粮田用量篇。", "有机肥优先。", "生石灰不进茶行。"],
    phenomenon: { appearance: "有人在茶行撒白粉，或计划按亩施一百公斤。", conditions: "粮田和茶园挨着的丘陵。", commonCrops: "茶叶。" },
    confuse: [
      { lookalike: "粮田石灰用量", difference: "粮田区间不能搬进茶园。", photoHint: "作物是茶还是稻麦。" },
      { lookalike: "茶园过酸需要少量改", difference: "过酸那篇才谈要不要改；这篇只谈禁忌。", photoHint: "先读茶园过酸篇。" },
    ],
    causes: { plainExplain: "茶园石灰像给小孩吃大人的退烧药，剂量错了比病更伤。", natural: ["茶树根系喜酸。"], human: ["图省事把粮田灰倒过来。" ] },
    dosage: [{ name: "茶园默认", range: "不按粮田石灰表", note: "确需改酸时只走茶园过酸篇的极低量" }],
    relatedSlugs: ["cha-yuan-guo-suan", "shi-hui-yong-liang", "suan-hua"],
    steps: ["停手，不要把粮田灰倒进茶行。", "测本园 pH。", "4.5～6.0 不改。", "确需改去过酸篇，不用这篇的邻田账。", "生石灰不进茶行。"],
    indicators: [{ name: "pH", meaning: "茶园自己的", typical: "不要用粮田目标" }],
  },
  "gen-fu-jian-bie": {
    uniqueAngle: "先看根再下肥",
    subtitle: "死棵先拔起来，别在叶上猜",
    summary: "点片死棵，先洗根：白、褐、臭、有没有瘤、茎基缢不缢。土问题、根腐、线虫、枯萎，根上就能分开。",
    fieldCheck: "到地里先看三样：叶位（新叶还是老叶）、根（白、褐还是臭）、土面（白霜、积水还是干裂）。三样对不上，不要急着下肥。",
    dontDo: ["死棵先追肥", "不拔根就当缺素", "看见萎蔫浇高浓度肥水"],
    whenToTest: "根褐臭或点片死棵时，先看根，再决定要不要测 EC、pH。",
    prevention: ["点片死棵保留病株给农技员看根。", "邻地轮作对照一张照片。", "肥水先停。"],
    phenomenon: { appearance: "点片萎蔫死棵，邻行可能还绿。", conditions: "连作棚、重茬田。", commonCrops: "番茄、黄瓜、草莓、瓜类。" },
    confuse: [
      { lookalike: "缺素黄叶", difference: "缺素成片按叶位；根腐点片、根先坏。", photoHint: "拔一棵洗根。" },
      { lookalike: "干旱", difference: "旱了土干、全田中午蔫；根腐土常还湿。", photoHint: "抓一把土，再看根。" },
    ],
    causes: { plainExplain: "叶子是告示牌，根是账本。账本不打开，告示牌上写什么都会猜错。", natural: ["土传病菌、线虫、渍水。"], human: ["连作、闷根、高盐肥。" ] },
    dosage: [{ name: "这篇不下肥", range: "先停肥看根", note: "分清后再进专篇" }],
    relatedSlugs: ["gen-jie-xian-chong", "tu-chuan-ku-wei", "huang-ye-jian-bie"],
    steps: ["拔病株洗根。", "白根少、褐臭→涝或腐。", "根上念珠→线虫。", "茎维管束褐→枯萎。", "土面白霜→先测 EC。"],
    indicators: [{ name: "根色", meaning: "第一刀", typical: "白/褐/臭" }, { name: "EC", meaning: "盐也伤根", typical: "棚里更要看" }],
  },
  "shi-fei-tiao-tu-rang": {
    uniqueAngle: "看叶能猜，不能代替测土",
    subtitle: "叶子是线索，化验单才是判决",
    summary: "叶位能缩小范围，不能给出公斤数。猜完必须测 pH、有机质、盐分/EC、再氮磷钾。",
    fieldCheck: "到地里先看三样：叶位（新叶还是老叶）、根（白、褐还是臭）、土面（白霜、积水还是干裂）。三样对不上，不要急着下肥。",
    dontDo: ["按叶色配一套完整施肥方案", "不取样只看邻地用什么", "微量元素叶面当当季主肥"],
    whenToTest: "任何准备下肥的当口，先看有没有近一年化验单；没有就取样。",
    prevention: ["叶色只用来选该进哪一篇。", "化验单按 pH→有机质→盐分→氮磷钾→微量的顺序读。", "叶面微肥只救急。"],
    phenomenon: { appearance: "有人拿着黄叶问该下什么肥。", conditions: "任何想省测土的时候。", commonCrops: "所有作物。" },
    confuse: [
      { lookalike: "黄叶鉴别", difference: "鉴别篇只分路；这篇强调分完仍要测土。", photoHint: "手里有没有化验单。" },
      { lookalike: "叶面微肥广告", difference: "喷叶不能改土。", photoHint: "问土测过没有。" },
    ],
    causes: { plainExplain: "叶子是路标，化验单是地图。路标能告诉你往哪拐，不能告诉你还要走几里。", natural: ["同一种黄叶背后数字不同。"], human: ["图省事按叶下肥。" ] },
    dosage: [{ name: "这篇不下肥", range: "不给公斤数", note: "去化验单篇和对应缺素篇" }],
    relatedSlugs: ["ce-tu-bao-gao", "huang-ye-jian-bie", "ye-cai-xiao-xing-yuan-su"],
    steps: ["叶位缩小范围。", "打开或去做化验单。", "按 pH、有机质、EC 先读。", "再对氮磷钾和微量。", "叶面只救急。"],
    indicators: [{ name: "化验单", meaning: "判决", typical: "pH / 有机质 / EC 优先" }],
  },
};
