#!/usr/bin/env python3
"""Download unique real field photos from Openverse + Wikimedia for Tuzhi covers."""
from __future__ import annotations

import hashlib
import json
import random
import time
import urllib.error
import urllib.parse
import urllib.request
from io import BytesIO
from pathlib import Path

from PIL import Image

UA = "TuzhiSoilLiteracy/1.0 (educational; contact g17612121666@gmail.com)"
ART = Path("/workspace/public/images/articles")
WIKI = Path("/workspace/public/images/wiki")
IMG = Path("/workspace/public/images")
ART.mkdir(parents=True, exist_ok=True)
WIKI.mkdir(parents=True, exist_ok=True)

SKIP_TITLE = (
    "shutterstock", "adobe stock", "getty", "alamy", "dreamstime", "istock",
    "123rf", "depositphotos", "vector", "clipart", "cartoon", "illustration",
    "icon set", "logo", "midjourney", "stable diffusion", "ai generated",
    "dall-e", "generated by", "watermark",
)
SKIP_URL = ("alamy", "dreamstime", "shutterstock", "istockphoto", "adobe.com", "gettyimages")

SLUGS = [
    "suan-hua","yan-jian","ban-jie","you-ji-zhi","que-dan","que-jia","que-lin","que-tie","que-xin",
    "lian-zuo","dashe-yanzhi","shao-gen","lao-hai","wei-sheng-wu","ce-tu-bao-gao","ce-tu-qu-yang",
    "que-gai","que-mei","que-peng","que-meng","que-liu","que-tong","que-mu","yang-fen-kang-kang",
    "yao-hai","miao-qi-fei-hai","an-hai","lv-hai","di-guan-nong-du","wei-fu-shu-you-ji-fei",
    "fan-yan","shi-hui-xing-tu","shi-gao-gai-jian","sha-tu-lou-fei","nian-tu-nan-geng","li-di-ceng",
    "hei-tu-tui-hua","jie-gan-huan-tian","shi-hui-yong-liang","xiu-shui-tian","qian-yu-tian",
    "shui-tian-huan-yuan","gen-fu-jian-bie","huang-ye-jian-bie","han-yan-jian-bie","cha-yuan-guo-suan",
    "ma-ling-shu-tu","sheng-wu-you-ji-fei","guo-yuan-tu-rang","da-peng-lian-zuo-zong-he",
    "hong-huang-rang-gai-suan","lv-du-shang-gen","suan-yu-que-gai","suan-tu-shi-lin",
    "sheng-li-suan-xing-fei","cha-yuan-shi-hui-jin-ji","su-da-yan-jian","bin-hai-yan-tu",
    "wei-xian-shui-guan-gai","di-biao-fu-yan","yan-jian-di-xuan-zuo","xi-yan-pai-shui",
    "da-peng-huan-tu-xi-yan","xuan-geng-bian-qian","shen-song-shi-ji","tu-rang-tuan-ju-ti",
    "ji-ya-che-zhe","ban-jie-yu-gen-xi","fu-gai-gai-zhi-di","lv-fei-fan-ya","sheng-wu-tan",
    "you-ji-fei-ru-he-xuan","jie-gan-bu-dan","hei-tu-you-ji-zhi-shou-hu","sha-tu-zeng-you-ji-zhi",
    "que-xin-yu-lin","que-peng-hua-er-bu-shi","qi-zi-huang-hua","pu-tao-shi-hui-tu-que-tie",
    "hua-sheng-kong-jia","ye-cai-xiao-xing-yuan-su","shui-dao-jiang-miao","yu-mi-miao-huang",
    "gen-jie-xian-chong","tu-chuan-ku-wei","qing-ku-bing-tu","cao-mei-lian-zuo","ping-guo-zai-zhi",
    "gao-wen-men-peng","han-lao-ji-zhuan","di-xia-shui-wei-gao","yu-hou-ban-jie-kai-lie",
    "leng-shui-guan-miao","yan-jiang-qi-hou-tu","shui-fei-yi-ti-hua-ec","ji-zhi-yu-tu-rang",
    "tu-rang-xiao-du-bian-jie","jian-yi-ph-ec","shi-fei-tiao-tu-rang","nan-fang-shui-tian-yang-fen",
]

Q: dict[str, list[str]] = {
    "suan-hua": ["stunted yellow wheat field", "acid soil crop damage", "yellow stunted seedlings farmland"],
    "yan-jian": ["saline soil white crust", "salt crust farmland", "alkali soil white surface"],
    "ban-jie": ["compacted soil clod field", "hard dry soil crust farmland", "soil compaction tractor"],
    "you-ji-zhi": ["pale sandy poor soil field", "thin topsoil eroded field", "light colored poor farmland"],
    "que-dan": ["nitrogen deficiency maize yellow", "yellow lower leaves corn field", "nitrogen deficient wheat"],
    "que-jia": ["potassium deficiency leaf scorch", "maize leaf margin necrosis", "leaf edge burn crop"],
    "que-lin": ["phosphorus deficiency purple maize", "purple corn seedlings", "phosphorus deficient plant"],
    "que-tie": ["iron chlorosis yellow leaf green veins", "citrus iron chlorosis", "soybean iron deficiency"],
    "que-xin": ["zinc deficiency maize white bud", "corn zinc deficiency", "zinc deficient maize"],
    "lian-zuo": ["wilted tomato plants greenhouse", "dead plants patchy field", "crop replant disease"],
    "dashe-yanzhi": ["greenhouse soil white salt", "plastic greenhouse tomato salt", "high tunnel soil crust"],
    "shao-gen": ["fertilizer burn seedlings", "seedling fertilizer damage", "burned crop leaves fertilizer"],
    "lao-hai": ["flooded vegetable field", "waterlogged crop standing water", "flooded paddy after rain"],
    "wei-sheng-wu": ["poor soil structure clod", "smeared wet soil no crumbs", "tired farmland soil"],
    "ce-tu-bao-gao": ["soil test report paper", "laboratory soil analysis sheet", "agronomy soil test form"],
    "ce-tu-qu-yang": ["soil sampling auger field", "farmer taking soil sample", "soil probe sampling"],
    "que-gai": ["tomato blossom end rot", "blossom-end rot fruit", "calcium deficiency tomato"],
    "que-mei": ["magnesium deficiency potato leaf", "interveinal chlorosis old leaf", "magnesium deficient maize"],
    "que-peng": ["boron deficiency plant hollow stem", "boron deficient broccoli", "crop boron deficiency flower"],
    "que-meng": ["manganese deficiency wheat", "manganese deficient soybean leaf", "crop manganese chlorosis"],
    "que-liu": ["sulfur deficiency canola yellow", "sulphur deficient plant new leaves", "yellow oilseed rape sulfur"],
    "que-tong": ["copper deficiency wheat ear", "copper deficient cereal", "wheat empty heads field"],
    "que-mu": ["molybdenum deficiency soybean", "yellow soybean nitrogen fixation", "legume pale leaves field"],
    "yang-fen-kang-kang": ["soil test high phosphorus", "unbalanced crop yellowing", "maize zinc lockout"],
    "yao-hai": ["herbicide injury twisted leaves", "pesticide burn crop leaf", "spray damage wrinkled seedling"],
    "miao-qi-fei-hai": ["seedling burn fertilizer", "uneven crop emergence", "scorched maize seedlings"],
    "an-hai": ["ammonia burn greenhouse leaves", "urea leaf scorch", "burned greenhouse tomato leaves"],
    "lv-hai": ["potato leaf scorch chloride", "potato field leaf margin burn", "chloride injury potato"],
    "di-guan-nong-du": ["drip irrigation tomato greenhouse", "dripper salt ring soil", "fertigation greenhouse"],
    "wei-fu-shu-you-ji-fei": ["raw manure pile field", "fresh manure on soil", "uncomposted manure crop"],
    "fan-yan": ["white salt after irrigation", "soil salt efflorescence", "dry salt crust irrigated field"],
    "shi-hui-xing-tu": ["calcareous soil white stones", "limestone farmland", "calcareous cropland"],
    "shi-gao-gai-jian": ["alkali soil gypsum", "sodic soil farmland", "white alkali spot field"],
    "sha-tu-lou-fei": ["sandy soil farmland", "sand soil in hand", "coarse sandy cropland"],
    "nian-tu-nan-geng": ["cracked clay soil field", "heavy clay farmland cracks", "sticky clay soil tillage"],
    "li-di-ceng": ["soil profile plough pan", "hardpan soil pit", "compacted soil layer profile"],
    "hei-tu-tui-hua": ["northeast black soil china", "chernozem eroded field", "thin black soil farmland"],
    "jie-gan-huan-tian": ["straw return to field", "rice straw incorporated soil", "maize residue on field"],
    "shi-hui-yong-liang": ["agricultural lime on field", "lime spreading farmland", "limestone powder soil"],
    "xiu-shui-tian": ["rusty water paddy", "iron oxide rice field water", "red water rice paddy"],
    "qian-yu-tian": ["gley soil paddy", "cold waterlogged paddy", "blue grey gleyed soil"],
    "shui-tian-huan-yuan": ["rice paddy black mud", "reduced paddy soil", "flooded rice field mud"],
    "gen-fu-jian-bie": ["root rot plant", "brown rotten crop roots", "diseased plant roots"],
    "huang-ye-jian-bie": ["yellow leaves crop field", "chlorosis comparison plants", "yellowing maize leaves"],
    "han-yan-jian-bie": ["wilted dry crop drought", "salt vs drought crop", "dry cracked soil wilted plant"],
    "cha-yuan-guo-suan": ["tea plantation hillside china", "tea garden rows", "camellia sinensis plantation"],
    "ma-ling-shu-tu": ["potato scab tuber", "common scab potato", "potato field harvest"],
    "sheng-wu-you-ji-fei": ["compost pile farm", "rotted manure compost", "farm compost soil"],
    "guo-yuan-tu-rang": ["orchard under tree soil", "fruit orchard grass alley", "apple orchard soil"],
    "da-peng-lian-zuo-zong-he": ["plastic greenhouse vegetables china", "greenhouse tomato wilt", "polytunnel crop"],
    "hong-huang-rang-gai-suan": ["red soil farmland china", "laterite cropland", "red yellow earth field"],
    "lv-du-shang-gen": ["damaged plant root tips", "brown root tips crop", "stunted roots soil"],
    "suan-yu-que-gai": ["tomato blossom end rot closeup", "calcium deficient fruit", "tomato black bottom rot"],
    "suan-tu-shi-lin": ["purple maize seedlings field", "phosphorus lockup acid soil", "stunted purple corn"],
    "sheng-li-suan-xing-fei": ["urea fertilizer granules field", "nitrogen fertilizer spreading", "farmer applying urea"],
    "cha-yuan-shi-hui-jin-ji": ["tea bushes soil", "tea plantation close", "tea garden soil surface"],
    "su-da-yan-jian": ["sodic soil column", "alkaline sodic farmland", "white alkali pan soil"],
    "bin-hai-yan-tu": ["coastal salt marsh farmland", "seaside saline soil", "coastal reclaimed saline land"],
    "wei-xian-shui-guan-gai": ["irrigated wheat saline", "brackish irrigation canal field", "irrigation canal farmland"],
    "di-biao-fu-yan": ["plastic mulch crop rows", "plastic film mulch maize", "mulched vegetable bed salt"],
    "yan-jian-di-xuan-zuo": ["salt tolerant crop field", "oilseed rape saline land", "crop on salt affected soil"],
    "xi-yan-pai-shui": ["drainage ditch farmland", "field drainage canal", "agricultural drain salt"],
    "da-peng-huan-tu-xi-yan": ["greenhouse soil replacement", "greenhouse tomato drip white", "solar greenhouse interior"],
    "xuan-geng-bian-qian": ["rotary tiller farmland", "rotavator tilling soil", "shallow tillage field"],
    "shen-song-shi-ji": ["subsoiler plough field", "deep ripping farmland", "chisel plow soil"],
    "tu-rang-tuan-ju-ti": ["soil crumbs in hand", "soil aggregate structure", "healthy soil crumbs"],
    "ji-ya-che-zhe": ["tractor wheelings field", "tire ruts farmland", "compacted tractor tracks soil"],
    "ban-jie-yu-gen-xi": ["crop roots hitting hardpan", "shallow roots compacted soil", "roots growing sideways soil"],
    "fu-gai-gai-zhi-di": ["straw mulch field", "plastic mulch cracked soil", "crop residue cover soil"],
    "lv-fei-fan-ya": ["green manure crop plow down", "cover crop incorporation", "vetch green manure field"],
    "sheng-wu-tan": ["biochar soil", "charcoal in soil", "biochar mixed farmland"],
    "you-ji-fei-ru-he-xuan": ["compost versus raw manure", "farmyard manure pile", "organic fertilizer bags field"],
    "jie-gan-bu-dan": ["straw on field yellow seedlings", "crop residue nitrogen", "maize stubble field"],
    "hei-tu-you-ji-zhi-shou-hu": ["black soil corn field", "mollisols farmland", "dark chernozem field"],
    "sha-tu-zeng-you-ji-zhi": ["sandy soil compost mix", "sand mixed with manure", "improving sandy farmland"],
    "que-xin-yu-lin": ["maize white bud zinc", "interveinal chlorosis maize", "high phosphorus crop field"],
    "que-peng-hua-er-bu-shi": ["tomato flowers no fruit", "poor fruit set tomato", "hollow stem broccoli boron"],
    "qi-zi-huang-hua": ["citrus yellow leaves orchard", "orange tree chlorosis", "citrus greening yellow shoot"],
    "pu-tao-shi-hui-tu-que-tie": ["grapevine iron chlorosis", "yellow grape leaves vineyard", "vineyard calcareous soil"],
    "hua-sheng-kong-jia": ["peanut empty pods", "peanut harvest field", "groundnut crop soil"],
    "ye-cai-xiao-xing-yuan-su": ["yellow spinach leaves", "leafy greens chlorosis", "vegetable leaf yellowing"],
    "shui-dao-jiang-miao": ["stunted rice seedlings paddy", "rice seedling yellow paddy", "rice transplanting field"],
    "yu-mi-miao-huang": ["yellow maize seedlings", "corn seedling chlorosis", "young corn yellow leaves"],
    "gen-jie-xian-chong": ["root knot nematode tomato", "galling roots tomato", "nematode damaged roots"],
    "tu-chuan-ku-wei": ["fusarium wilt tomato stem", "vascular browning plant stem", "wilted tomato plant"],
    "qing-ku-bing-tu": ["bacterial wilt tomato", "sudden wilt tomato field", "tomato plant collapse"],
    "cao-mei-lian-zuo": ["strawberry greenhouse plants", "strawberry wilt field", "strawberry plastic tunnel"],
    "ping-guo-zai-zhi": ["apple orchard replant", "old apple tree stump soil", "apple orchard soil pit"],
    "gao-wen-men-peng": ["solarization plastic soil", "greenhouse soil covered plastic", "soil solarisation tarp"],
    "han-lao-ji-zhuan": ["cracked mud after flood", "flood then drought field", "dried puddle farmland"],
    "di-xia-shui-wei-gao": ["water seeping soil pit", "high water table field", "wet soil excavation"],
    "yu-hou-ban-jie-kai-lie": ["soil crust after rain", "capped soil seedlings", "crusted soil emergence"],
    "leng-shui-guan-miao": ["rice irrigation inlet", "paddy water inlet seedlings", "irrigating rice field"],
    "yan-jiang-qi-hou-tu": ["riverside paddy field", "wetland rice along river", "alluvial paddy landscape"],
    "shui-fei-yi-ti-hua-ec": ["fertigation drip greenhouse", "drip irrigation fertilizer tank", "hydroponic EC meter"],
    "ji-zhi-yu-tu-rang": ["coconut coir substrate bags", "soilless culture greenhouse", "grow bags greenhouse"],
    "tu-rang-xiao-du-bian-jie": ["soil fumigation tarp field", "plastic covered soil disinfection", "steam soil treatment"],
    "jian-yi-ph-ec": ["soil pH test kit field", "pH paper soil slurry", "handheld EC meter soil"],
    "shi-fei-tiao-tu-rang": ["farmer reading soil test", "comparing yellow leaf soil report", "agronomist with soil sample"],
    "nan-fang-shui-tian-yang-fen": ["southern china rice paddy", "flooded rice terraces", "paddy soil profile"],
}

WIKI_Q = {
    "ph": ["soil pH meter field", "testing soil acidity"],
    "om": ["dark organic soil hand", "humus rich soil"],
    "cec": ["clay soil farmland", "heavy clay cropland"],
    "texture": ["soil texture sand silt clay", "loam soil in hand"],
    "aggregate": ["soil crumbs aggregates", "granular soil structure"],
    "n": ["nitrogen deficient maize", "yellow corn lower leaves"],
    "alkn": ["soil test nitrogen", "fertilizer nitrogen field"],
    "p": ["phosphorus deficient corn purple", "purple maize seedlings"],
    "avp": ["phosphate fertilizer granules", "banded fertilizer maize"],
    "k": ["potassium deficient maize leaf", "leaf margin scorch crop"],
    "avk": ["potash fertilizer field", "crop potassium deficiency"],
    "ca": ["blossom end rot tomato", "calcium deficient fruit"],
    "al": ["acid soil stunted roots", "aluminium toxic soil"],
    "zn": ["zinc deficiency corn", "maize white bud"],
    "b": ["boron deficiency crop", "hollow stem plant"],
    "ec": ["soil EC meter", "electrical conductivity soil"],
    "salt": ["saline soil crust", "salt crystals soil"],
    "bulk": ["soil bulk density core", "soil core sample"],
    "test": ["soil testing laboratory", "soil sample bags"],
    "saline": ["saline alkali land", "white salt farmland"],
    "acid": ["acid soil crop", "liming acid soil"],
    "compaction": ["soil compaction layer", "plough pan profile"],
    "mg": ["magnesium deficiency leaf", "interveinal chlorosis"],
    "fe": ["iron chlorosis citrus", "yellow leaf green veins"],
    "mn": ["manganese deficiency wheat", "manganese chlorosis"],
    "s": ["sulfur deficiency canola", "yellow oilseed rape"],
    "cu": ["copper deficiency cereal", "wheat poor grain fill"],
    "mo": ["molybdenum deficiency clover", "yellow soybean leaves"],
    "porosity": ["soil pores structure", "aerated soil crumbs"],
    "fc": ["soil water holding", "moist loam field capacity"],
    "gley": ["gleyed soil profile", "grey waterlogged soil"],
    "replant": ["replant disease orchard", "continuous cropping greenhouse"],
}

EXTRA = {
    "hero-field": (IMG / "hero-field.jpg", ["tilled farmland soil", "freshly plowed field", "cultivated brown soil"]),
    "healthy-soil": (IMG / "healthy-soil.jpg", ["healthy soil in hands", "dark loam crumbs", "rich garden soil"]),
    "soil-profile": (IMG / "soil-profile.jpg", ["soil profile pit horizons", "soil pit layers", "soil horizon photograph"]),
    "olivine": (IMG / "olivine.jpg", ["olivine mineral crystal", "peridot crystal specimen", "green olivine rock"]),
}

used_hash: set[str] = set()
used_url: set[str] = set()


def get(url: str, timeout: int = 25) -> bytes | None:
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "*/*"})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            if e.code == 429:
                time.sleep(12 + attempt * 8)
                continue
            return None
        except Exception:
            time.sleep(1.5)
    return None


def bad_meta(title: str, url: str) -> bool:
    t = (title or "").lower()
    u = (url or "").lower()
    if any(s in t for s in SKIP_TITLE):
        return True
    if any(s in u for s in SKIP_URL):
        return True
    return False


def openverse(q: str, pages: int = 2) -> list[dict]:
    out = []
    for page in range(1, pages + 1):
        qs = urllib.parse.urlencode(
            {"q": q, "page_size": 20, "page": page, "mature": "false", "license_type": "all"}
        )
        raw = get(f"https://api.openverse.org/v1/images/?{qs}")
        time.sleep(0.35)
        if not raw:
            continue
        try:
            data = json.loads(raw.decode("utf-8", "replace"))
        except Exception:
            continue
        for it in data.get("results") or []:
            url = it.get("url") or ""
            title = it.get("title") or ""
            if not url or bad_meta(title, url):
                continue
            out.append({"url": url, "title": title, "id": it.get("id")})
    return out


def wikimedia(q: str) -> list[dict]:
    qs = urllib.parse.urlencode(
        {
            "action": "query",
            "generator": "search",
            "gsrsearch": q,
            "gsrnamespace": 6,
            "gsrlimit": 12,
            "prop": "imageinfo",
            "iiprop": "url|size|mime",
            "iiurlwidth": 1600,
            "format": "json",
        }
    )
    raw = get(f"https://commons.wikimedia.org/w/api.php?{qs}")
    time.sleep(0.3)
    if not raw:
        return []
    try:
        data = json.loads(raw.decode("utf-8", "replace"))
    except Exception:
        return []
    out = []
    pages = (data.get("query") or {}).get("pages") or {}
    for p in pages.values():
        info = (p.get("imageinfo") or [{}])[0]
        url = info.get("thumburl") or info.get("url") or ""
        title = p.get("title") or ""
        mime = (info.get("mime") or "").lower()
        if not url or "image/" not in mime:
            continue
        if bad_meta(title, url):
            continue
        out.append({"url": url, "title": title, "id": title})
    return out


def save_unique(src: bytes, dest: Path) -> bool:
    try:
        im = Image.open(BytesIO(src))
        im = im.convert("RGB")
    except Exception:
        return False
    w, h = im.size
    if min(w, h) < 220:
        return False
    # skip near-solid / tiny-detail
    if w * h < 80_000:
        return False
    im.thumbnail((1400, 1400))
    buf = BytesIO()
    im.save(buf, "JPEG", quality=84, optimize=True)
    data = buf.getvalue()
    hsh = hashlib.md5(data).hexdigest()
    if hsh in used_hash:
        return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(data)
    used_hash.add(hsh)
    return True


def candidates(queries: list[str]) -> list[dict]:
    pool: list[dict] = []
    seen = set()
    for q in queries:
        for fn in (openverse, wikimedia):
            for it in fn(q):
                u = it["url"]
                if u in seen or u in used_url:
                    continue
                seen.add(u)
                pool.append(it)
    random.shuffle(pool)
    # prefer flickr / wikimedia
    def rank(it: dict) -> int:
        u = it["url"]
        if "wikimedia" in u or "wikipedia" in u:
            return 0
        if "flickr" in u or "staticflickr" in u:
            return 1
        return 2
    pool.sort(key=rank)
    return pool


def assign(dest: Path, queries: list[str]) -> bool:
    for it in candidates(queries):
        raw = get(it["url"], timeout=30)
        if not raw:
            continue
        if save_unique(raw, dest):
            used_url.add(it["url"])
            print("OK", dest.name, it["title"][:70])
            return True
    print("FAIL", dest.name, queries[0])
    return False


def main() -> None:
    # preload hashes of files we keep only if unique later — we overwrite all
    random.seed(29)
    report = {"ok": [], "fail": []}
    print("slugs", len(SLUGS))
    for slug in SLUGS:
        qs = Q.get(slug) or [slug.replace("-", " ") + " farmland"]
        dest = ART / f"{slug}.jpg"
        if assign(dest, qs):
            report["ok"].append(slug)
        else:
            report["fail"].append(slug)
        dest2 = ART / f"{slug}-2.jpg"
        qs2 = list(reversed(qs)) + [qs[0] + " closeup", "farmland soil surface"]
        assign(dest2, qs2)
    for wid, qs in WIKI_Q.items():
        dest = WIKI / f"{wid}.jpg"
        if assign(dest, qs):
            report["ok"].append("wiki-" + wid)
        else:
            report["fail"].append("wiki-" + wid)
        assign(WIKI / f"{wid}-2.jpg", list(reversed(qs)) + ["soil field"])
    for key, (path, qs) in EXTRA.items():
        if assign(path, qs):
            report["ok"].append(key)
        else:
            report["fail"].append(key)
    Path("/tmp/photo-report.json").write_text(json.dumps(report, indent=2))
    # uniqueness of primary covers
    prim = {}
    for slug in SLUGS:
        p = ART / f"{slug}.jpg"
        if not p.exists():
            print("MISSING", slug)
            continue
        h = hashlib.md5(p.read_bytes()).hexdigest()
        prim.setdefault(h, []).append(slug)
    dups = {k: v for k, v in prim.items() if len(v) > 1}
    print("primary unique", len(prim), "dups", len(dups), "fail", report["fail"])
    if dups:
        print("DUP", dups)


if __name__ == "__main__":
    main()
