# Unique kernels for wrap_zh / wrap_en. Imported via exec() into build_lf.py.

k("suan-hua","洗根看尖：褐秃少白尖才像铝在咬，锈水是加分项。","雨水淋走钙镁，铵态氮年年加账，有机质薄了土更酸。","测 0～20 厘米 pH，低于 5.5 才改，石灰分两次，看新根再薄肥。","茶园不要按粮田改到中性；根秃时不要猛尿素。",
  "Wash root tips: brown and bald means aluminium, rusty water is extra evidence.","Rain strips bases, ammonium-N adds to the bill, thin organic matter sours faster.","Test 0–20 cm pH; lime only below 5.5, split, wait for white new roots.","Don’t push tea to neutrality; don’t pour urea on bald roots.")
k("yan-jian","土面白霜、出苗花斑、叶缘像开水烫；小水有时更蔫。","根靠浓度差喝水，土太咸水被抢走；咸看 EC，涩看 pH 和钠。","有排水再洗，覆盖断返盐，肥要淡，盐斑上停高盐肥。","没沟不要大水漫灌；见白霜不要一律撒石膏。",
  "White frost, patchy emergence, scalded margins; a small drink may wilt more.","Roots drink by a gradient; salt steals the water. Salt is EC, alkali is pH and sodium.","Leach only with drainage, mulch, keep fertiliser dilute.","Don’t flood without a ditch; don’t gypsum every white crust.")
k("ban-jie","锄不动、雨后积水、根横走；车辙里常常不出苗。","旋耕只剪头发，下面压出犁底层；有机质是胶水，胶没了就板。","适墒隔年深松，刚过硬盖就停，大约 25～40 厘米，配有机肥覆盖。","泥里不要进车；不要年年把生土翻上来。",
  "Hard hoe, ponding, sideways roots; ruts often stay blank.","Rotary tillage is a haircut and irons a pan; organic matter is the glue.","Subsoil at crumb-moist in alternate years, just through the pan, about 25–40 cm, with organic matter.","Stay off mud; don’t invert raw subsoil yearly.")
k("you-ji-zhi","土色发浅、一抓就散、肥效年年飘，雨后表面结壳。","有机质是土的肉和缓冲。肉薄了，肥留不住，菌也没房住。","连续三年还田加腐熟粪，比一季堆满靠谱；覆盖少裸冬。","不要指望一袋菌一季翻身；生粪埋根边会烧苗。",
  "Pale colour, powdery feel, fertiliser ‘evaporates’, crust after rain.","Organic matter is meat and buffer. Thin meat cannot hold nutrients or biology.","Three years of straw and rotted manure beat one mountain of dung. Cover, less bare winter.","A microbe bag will not rebuild a house in one season; raw manure by the root burns.")
k("que-dan","下部老叶匀黄、新叶还绿，植株瘦、分蘖少。根白才像缺氮。","氮会搬家，老叶把氮送给新叶。沙土一次倒全年留不住。","根不坏才少量多次。叶面按说明救急，沙土分顿。","根黑臭时不要猛尿素。新叶也黄要想缺硫或缺铁。",
  "Old leaves yellow first, new leaves greener, thin plants. White roots fit nitrogen.","Nitrogen moves: old leaves donate. Sand cannot hold a season in one pour.","Only feed when roots are sound, little and often, foliar as a rescue on the label.","Don’t pour urea on black stinking roots. New-leaf yellow may be sulphur or iron.")
k("que-jia","老叶叶缘焦枯像火燎，向内卷，茎软果不甜。土面不一定白。","钾管气孔和糖分。缺了叶边先焦。盐害也焦边，但常有白霜和出苗差。","测速效钾。叶面磷酸二氢钾先小面积。秸秆能还就还。","忌氯作物不要用氯化钾；中午不要喷浓钾；见焦边不要一律当缺钾。",
  "Old-leaf margins scorch like fire and roll in; stems soft, fruit not sweet. Surface need not be white.","Potassium runs stomata and sugar. Salt also scorches margins but usually with frost and poor emergence.","Test available K. Foliar potassium dihydrogen phosphate on a small patch. Return straw.","No potassium chloride on chloride-sensitive crops; don’t spray strong K at noon; don’t treat every scorch as K.")
k("que-lin","苗期紫红发僵，叶暗绿，根短少。回暖仍不发棵。","磷管生根。酸土被铁铝钉住，钙质土被钙钉住，土里有磷根摸不着。","测有效磷和 pH。酸则先少量改酸，磷肥条施穴施在根旁。苗期叶面只救急。","不要满地撒磷不管 pH；不要石灰和磷肥同一天混堆。",
  "Seedlings purple, dark green, stunted, few roots. Warmth does not restart them.","Phosphorus is for roots. Acid soils nail it with iron and aluminium; calcareous soils nail it with calcium.","Test P and pH. Lime a little if acid, band P by the root. Foliar P is only a rescue.","Don’t broadcast P on untested pH; don’t heap lime and phosphate the same day.")
k("que-tie","新叶黄、叶脉还绿，顶端更明显。老叶相对还绿。","高 pH 把铁锁住。土里有铁，根吃不到。缺氮是老叶先黄，路不一样。","叶面螯合铁按说明重复救急。根际靠有机肥和稳定水分，不要大水漫灌。","高 pH 土不要猛撒硫酸亚铁当当季解决；不要一黄就冲尿素。",
  "New leaves yellow with green veins, worst at the tip. Old leaves stay greener.","High pH locks iron. The soil has iron; the root cannot eat it. Nitrogen yellows old leaves first — a different road.","Chelated foliar iron on the label, repeated. Organic matter in the root zone, no flood irrigation.","Don’t dump ferrous sulphate on high-pH soil as a season fix; don’t chase yellow with urea.")
k("que-xin","新叶脉间失绿、节间短、小叶簇生，玉米花白苗最典型。","锌走生长点。高磷会把门堵住。石灰性土、高 pH 更常见。","叶面百分之零点一到零点二量级，先小面积。土施数年一次，按测土。高磷先停。","不要花白苗当药害乱喷；不要锌肥年年倒。",
  "Interveinal yellow on new leaves, short internodes, little leaves clustered; maize white-bud is the type.","Zinc feeds the growing point. High phosphorus crowds the door. Calcareous high-pH soils show it more.","Foliar zinc around 0.1–0.2%, small patch first. Soil zinc once in years from a test. Stop excess P.","Don’t treat white-bud as pesticide injury; don’t pour zinc every year.")
k("lian-zuo","同一茬越种越差，点片死棵，邻地轮作的却好。根上可能有结或褐腐。","重茬把病菌、线虫、盐和偏肥熬在一口锅里。菌剂代替不了换科轮作。","先看根。轮作换科最稳。棚里还要看盐。用药去农技站按标签，这里不开方。","病株不要留在地里；不要点片死棵还猛追肥。",
  "The same crop gets worse; patch death while a rotated neighbour is fine. Knots or brown rot on roots.","Replant stews pathogens, nematodes, salt and lopsided fertiliser. A microbe bag is not a rotation.","Read the root. Rotate family. In houses, read salt too. Products only via extension and the label — no recipes here.","Don’t leave dead plants; don’t pour fertiliser on patch death.")
k("dashe-yanzhi","膜下白霜、滴口一圈、越浇越蔫。揭开膜能看见盐霜。","大棚是盆，盐排不出去。底肥拍胸脯、滴灌越浓，盆就越咸。","测 EC。能揭膜淋雨或有排水就洗。平时薄肥勤施，停生粪和高盐肥。","白霜上不要再加一把复合肥；不要全年不揭膜。",
  "White frost under film, a ring at the dripper, more wilt after watering.","A greenhouse is a bowl; salt cannot leave. Heavy base dressing and strong drip make the bowl saltier.","Test EC. Rain or leach if you can drain. Thin feeds, no raw manure, no high-salt fertiliser.","Don’t throw compound on the frost; don’t keep the film on all year.")
k("shao-gen","施肥几天内叶焦根黑，种沟能见肥粒。沿肥带成行。","肥把根周围做成盐水。沙土、种肥贴种子、一次过浓最伤。","立刻灌清水稀释，暂时停肥。补种要隔离肥带。种肥和种子隔开。","烧了还补肥会更烧；沙土不要按黏土用量。",
  "Leaf scorch and black root tips within days of fertiliser; granules visible in the seed furrow, in a stripe.","Fertiliser turns the root zone into brine. Sand, fertiliser against the seed, and one strong hit hurt most.","Flush with clean water, pause fertiliser. Re-sow away from the band. Keep seed and fertiliser apart.","Don’t add more fertiliser after a burn; don’t use clay rates on sand.")
k("lao-hai","白天蔫晚上缓，田里有明水或底湿，根黑臭。土是湿的还蔫。","根要氧气。水把气排走，根就闷死。湿土再浇是火上浇油。","先排水。等新根出来再叶面薄肥。破犁底层托水。低洼先挖沟。","土湿不要当旱浇；涝后不要立刻猛氮。",
  "Wilt by day, recover at night, standing water or a wet bottom, roots black and smelling. Wet soil and still wilted.","Roots need air. Water pushes air out and the root smothers. Watering wet soil pours fuel on the fire.","Drain first. Thin foliar feed only after new roots. Break a pan that perches water. Ditch the low spots.","Don’t irrigate wet soil as if it were drought; don’t dump nitrogen the day after a flood.")
k("wei-sheng-wu","养分不低却长不好，秸秆一年不烂，土臭发黏没孔隙。","菌要房要饭。板、酸、咸、没有机质，倒菌也住不下。先改物理化学，菌才回来。","先排水通气、上腐熟有机肥、把 pH 和盐放到活得住的区间。菌剂按登记证，不当事的唯一修理。","不要菌和杀菌剂一起倒；不要暴晒后随手撒；不要不给有机质只倒菌。",
  "Nutrients not low but growth poor; straw sits a year; soil smells, smears, no pores.","Microbes need a house and a meal. Compaction, acid, salt and no organic matter mean a bag cannot settle. Fix physics and chemistry first.","Drain, air, rotted organic matter, pH and salt in a living range. Use only registered products — not as the only repair.","Don’t mix microbes with a sterilant; don’t toss them on baked soil; don’t skip organic matter.")
k("ce-tu-bao-gao","化验单先读 pH、有机质、盐分，再读氮磷钾和微量元素。单位看错一位会下错肥。","报告是尺子不是处方。分级按当地，跨省死套会错。缺一项不等于按最大量补。","阅读顺序：pH → 有机质 → 盐分 → 氮磷钾 → 微量元素。看不懂带去农技站。先改极端项。","不要报告写缺就按最大量补；不要单位看错；不要把邻省标准当自家的。",
  "Read pH, organic matter and salt first, then NPK and micronutrients. A missed decimal poisons the rate.","A sheet is a ruler, not a prescription. Local classes matter. ‘Low’ is not a licence for the maximum.","Order: pH → organic matter → salt → NPK → micronutrients. Take it to extension if you cannot read it. Fix extremes first.","Don’t fill every ‘low’ at the maximum; don’t misread units; don’t paste another province’s table onto your field.")
k("ce-tu-qu-yang","取样错了，后面全错。一个坑、粪堆边、田边，都不能代表这块地。","土是花的。8～15 个点混合，才像这块地的平均饭量。表层和犁底层不要胡乱混。","S 形或棋盘 8～15 点，0～20 厘米，避开田边粪堆。四分法留一袋，写清地块作物日期。施肥改土前取。","不要只挖一个坑；不要挖粪堆边；不要把犁底层和表土搅在一袋。",
  "A bad sample poisons every later decision. One hole, a manure heap, a field edge — none of those is the field.","Soil is patchy. Eight to fifteen spots mixed are the field’s average meal. Don’t mix topsoil with the pan.","S-shape or grid, 8–15 spots, 0–20 cm, skip edges and heaps. Quarter down to one bag. Label field, crop, date. Sample before you treat.","Don’t dig one hole; don’t sample the manure pile; don’t mix pan and topsoil in one bag.")
k("que-gai","顶芽停、脐腐、裂果、心叶焦边。老叶相对还好。忽干忽湿更明显。","钙像砌墙的砖，摆上就不大搬家。干旱、铵态氮、盐、酸，都会让生长点吃不到。","先稳定浇水。叶面钙喷幼果和心叶，按包装下限，先小面积。酸土问 pH 和土壤钙，不要只打叶面。","脐腐不要当病害猛打药；缺钙时不要猛冲尿素。",
  "Growing point stops, blossom-end rot, split fruit, scorched heart leaves. Old leaves relatively fine. Worse with wet-dry swings.","Calcium is a brick that barely moves. Drought, ammonium-N, salt and acid keep it from the tip.","Steady the water first. Foliar calcium on young fruit and heart leaves at the label floor, small patch. On acid soil ask pH and soil calcium — a spray is not the soil job.","Don’t treat blossom-end rot as a pathogen; don’t chase calcium lack with urea.")
k("que-mei","老叶脉间黄、叶脉还绿，从下部开始。不要当成缺铁。","镁在叶绿素里。钾太高会把镁挤掉。缺铁走新叶，缺镁走老叶。","测交换性镁和钾。钾高先把钾降下来。叶面百分之零点五到一量级硫酸镁，先小面积。","不要老叶脉间黄当缺铁；不要高钾还猛钾；不要不测就土里大把硫酸镁。",
  "Old leaves yellow between green veins, from the bottom up. That is not iron.","Magnesium sits in chlorophyll. High potassium crowds it out. Iron hits new leaves; magnesium hits old ones.","Test magnesium and potassium. Drop excess K first. Foliar magnesium sulphate around 0.5–1%, small patch.","Don’t treat old-leaf striping as iron; don’t pour more K; don’t dump magnesium sulphate without a test.")
k("que-peng","花而不实、蕾铃掉、茎空心或裂，生长点萎缩。","硼管开花结实。缺和毒只隔一层纸。沙土、干旱更容易缺。","先看墒和盐。叶面硼按包装下限分两次。土施常见每亩 0.5～1 公斤量级硼砂，按测土宁少勿多。","绝不能加倍；干旱没墒不要先猛硼；无化验不要土里一把倒。",
  "Bloom without fruit, dropped buds, hollow or split stems, growing point stalled.","Boron runs flowering. Deficiency and toxicity are a thin window. Sand and drought show lack more.","Check moisture and salt first. Foliar boron at the label floor, twice. Soil borax often 0.5–1 kg/mu from a test — better too little.","Never double boron; don’t pour boron onto dry soil; don’t broadcast without a test.")
k("que-meng","新叶脉间失绿，常带褐斑或灰白小点。小麦上更常见。","锰在新叶。过酸或过碱都会乱。有机质很高的石灰性土有时也锁锰。","测有效锰和 pH。叶面按说明先小面积。先改极端 pH，不要只喷。","不要和缺铁、缺锌混成一瓶猛喷；不要不看 pH 只补锰。",
  "New leaves yellow between veins, often with brown or grey specks. Wheat shows it clearly.","Manganese is a new-leaf story. Too acid or too alkaline both scramble it. High-organic calcareous soils can lock it too.","Test manganese and pH. Foliar on the label, small patch. Fix extreme pH; don’t only spray.","Don’t tank-mix it with iron and zinc as a blast; don’t skip pH and only add manganese.")
k("que-liu","整株偏黄，新叶也黄，和缺氮只黄老叶相反。","硫不容易从老叶搬到新叶。缺氮老叶先黄，缺硫新老一起黄。沙土、高氮更容易显。","先分清叶位。测硫或看肥料是否长期不含硫。按农技站补硫酸盐类，宁少勿多。","不要一律当缺氮猛尿素；尿素本身不含硫，会越补越不像。",
  "The whole plant pales, including new leaves — the opposite of nitrogen’s old-leaf yellow.","Sulphur does not move from old leaves to new. Nitrogen yellows old leaves first; sulphur yellows new and old together. Sand and high N show it more.","Read leaf position. Test sulphur or check whether fertiliser has been sulphur-free for years. Sulphate sources via extension, better too little.","Don’t treat it as nitrogen and pour urea; urea has no sulphur and makes the picture worse.")
k("que-tong","叶尖发白卷曲，穗不实、结实差。新叶先出事。","铜在花和穗。有机质很高的沙土、过酸过碱都可能缺。","测有效铜。叶面按包装下限，先小面积。不要土里猛倒。","不要把穗不实都当病害打药；铜缺和铜毒窗口也不宽。",
  "Leaf tips bleach and curl; ears set poorly. New leaves go first.","Copper sits in flowers and ears. Very organic sands, and soils too acid or too alkaline, can run short.","Test copper. Foliar at the label floor, small patch. Don’t dump it on the soil.","Don’t treat every blank ear as a disease; copper’s toxic window is not wide either.")
k("que-mu","豆科叶片畸形发黄，固氮差、植株瘦。新叶皱缩。","钼帮豆科固氮。过酸土钼被锁，过石灰又是另一套乱。","先测 pH。过酸按改酸文少量改。钼酸铵叶面按说明，极低量，先小面积。","不要豆叶黄了就猛氮；钼是微量，加倍会出事。",
  "Legume leaves distort and yellow; nodulation poor; plants thin. New leaves crinkle.","Molybdenum helps legumes fix nitrogen. Too-acid soil locks it; overliming scrambles another set.","Test pH first. If too acid, lime a little per the acid guide. Foliar ammonium molybdate on the label — tiny rates, small patch.","Don’t pour nitrogen on yellow beans as the first move; molybdenum is a trace — doubling hurts.")
k("yang-fen-kang-kang","化验单某一项极高，作物却表现另一项的缺素。磷很高锌进不来，钾很高镁被挤。","养分排队进同一扇门。人多的把门堵住。一张‘很肥’的单子仍能黄。","先把过高的停下来。被锁的那项叶面救急。下一年按整张单子平衡，不要按去年习惯。","不要缺什么加什么同时还在猛加已经过高的那项。",
  "One column on the sheet is off the chart; the crop shows the missing one. High P, little zinc. High K, little magnesium.","Nutrients queue at the same door. A crowd blocks the door. A ‘rich’ sheet can still yellow.","Stop pouring the high one. Foliar-rescue the locked one if the crop is in season. Next year, a balanced plan from the whole sheet.","Don’t add the missing one while still pouring whatever is already extreme.")
k("yao-hai","喷完药几天内斑、扭、心叶畸形，来得快，不像慢慢缺素。问最近喷了什么。","药害是外来一巴掌。缺素是慢慢亏。斑扭不规则、有喷药史，就先停药。","先停喷。清水淋洗能淋的叶。对照没喷到的行。拿不准带药瓶去农技站，这里不开方。","不要药害上再加一遍药；不要把扭曲当缺锌猛补。",
  "Spots, twist and heart-leaf distortion within days of a spray — fast, not a slow deficiency. Ask what was sprayed.","A pesticide slap is sudden. A deficiency is a slow bill. Irregular twist plus a spray history: stop spraying first.","Stop the spray. Rinse leaves you can. Compare unsprayed rows. Unsure: take the bottle to extension. No recipes here.","Don’t spray again on injury; don’t treat twist as zinc and pour more.")
k("miao-qi-fei-hai","出苗不齐、小苗叶子焦、根尖发黑。种肥贴种子最常见。","小苗根短，一点点浓盐就能腌死。沙土更狠。","灌清水稀释，停肥。补种隔离肥带。种肥与种子隔开，沙土按下限。","不要出苗不齐还补肥；不要把烧苗当病害打药。",
  "Patchy emergence, scorched baby leaves, black root tips. Fertilizer against the seed is the usual story.","A seedling root is short; a little brine pickles it. Sand is harsher.","Flush, pause fertiliser, re-sow off the band. Keep seed and fertiliser apart; sand at the floor of the range.","Don’t fertilise a burn; don’t treat a burn as a disease.")
k("an-hai","棚内叶缘焦像烟熏，刚施肥就熏，嫩叶更重。有氨味。","未腐熟粪、碳铵、尿素表施遇湿，氨气往上走。设施更闷。","先通风。停这次肥。腐熟再进棚。碳铵不要表施在密闭棚。","不要关棚猛氨肥；不要闻着呛还补肥。",
  "Leaf margins look smoked inside a house, right after fertiliser, worst on young leaves, ammonia smell.","Raw manure, ammonium bicarbonate, or surface urea in the wet sends ammonia up. A closed house traps it.","Vent first. Skip this feed. Only rotted manure indoors. Don’t surface-apply ammonium bicarbonate in a shut house.","Don’t shut the house and pour ammonia fertiliser; don’t feed again while it still stings the nose.")
k("lv-hai","忌氯作物叶缘焦，问最近用了什么含氯化肥。马铃薯、烟草、部分果树更敏感。","氯跟着水走。过量叶缘焦。盐害也焦，但氯害要问肥料袋。","翻肥料包装。忌氯作物改用硫酸钾等，按农技站。已伤的先灌水稀释，停含氯肥。","不要忌氯作物上氯化钾当钾源；不要焦边一律当缺钾。",
  "Chloride-sensitive crops scorch at the margin. Ask which chloride fertiliser was used. Potato, tobacco, some fruit are touchy.","Chloride rides with water. Excess scorches margins. Salt also scorches — the bag tells chloride apart.","Read the bag. Switch chloride-sensitive crops to sulphate-K via extension. Dilute what is already there; stop chloride fertiliser.","Don’t use potassium chloride on chloride-sensitive crops; don’t treat every scorch as potassium lack.")
k("di-guan-nong-du","滴头附近白圈烧根，午后萎蔫，滴口更重。越浇越伤。","滴灌是细水，浓度高了就是在腌根。EC 超了不是更有劲。","测灌溉水和土壤 EC。降低浓度，加大灌量把盐推开。苗期更淡。","不要越浓越有劲；不要滴口白圈上再加肥。",
  "A white ring at the dripper burns roots; afternoon wilt, worse at the emitter. More water-fertiliser makes it worse.","Drip is a sip. Too strong and you pickle the root. High EC is not ‘more power’.","Test water and soil EC. Drop the concentration, push a larger drink to move salt out. Seedlings even more dilute.","Don’t chase strength; don’t fertilise the white ring.")
k("wei-fu-shu-you-ji-fei","生粪堆边苗像被烫，粪还臭，土发热。根焦。","未腐熟会抢氮、发热、带盐带氨。当宝埋到根边，就是烧苗。","停用这块生粪。腐熟到不烫手不熏眼再进地。发热期不要盖根。","不要把生粪当宝埋根；不要未腐熟和种子同沟。",
  "Seedlings look scalded beside a raw dung heap; it still smells; the soil is hot; roots scorch.","Raw manure steals nitrogen, runs a fever, brings salt and ammonia. Buried by the root it is a burn.","Stop this batch. Compost until it is not hot and does not sting the eyes. Don’t cover roots while it heats.","Don’t bury raw manure as treasure; don’t put it in the seed furrow.")
k("fan-yan","浇完晒干，地表一层白。苗更焦边。干湿交界最白。","水是电梯，盐是乘客。蒸发把盐送到表面。小水勤浇最会返。","灌就灌透并有出路。覆盖、中耕断毛细管。春季最要紧。","不要浇完又让太阳把盐晒上来还接着小水勤浇。",
  "After irrigation dries, a white film; margins worse. The wet-dry edge is whitest.","Water is the lift, salt the passenger. Evaporation delivers salt to the surface. Small frequent drinks raise it most.","If you irrigate, irrigate through and give an outlet. Mulch and cultivate to cut capillaries. Spring is the season.","Don’t follow a drying crust with another tiny drink.")
k("shi-hui-xing-tu","土并不瘦，叶子却黄，尤其新叶脉绿。pH 常常大于 7.5。","石灰性土把铁锰锌锁住。化验全量不低，有效量低。","不要按缺氮猛冲尿素。叶面螯合微肥救急。根际有机质、稳定水分，磷不要再堆。","不要高 pH 土猛撒硫酸亚铁；不要一黄就当氮不够。",
  "The soil is not poor, yet leaves yellow — especially new leaves with green veins. pH often above 7.5.","Calcareous soil locks iron, manganese and zinc. Total numbers look fine; available numbers do not.","Don’t chase it with urea. Chelated foliar micronutrients as rescue. Organic matter in the root zone, steady water, stop stacking phosphorus.","Don’t dump ferrous sulphate on high pH; don’t treat every yellow as nitrogen.")
k("shi-gao-gai-jian","pH 很高、湿泥干板、出苗差，才像碱化土。石膏是给碱的，不是给所有白霜的。","石膏里的钙把钠换下来，还要靠水把钠洗走。没有排水，石膏白撒。盐土的正道是灌排。","化验确认碱化再考虑石膏。用量按测土，宁少勿多，先小片。必须有排水。","酸土不要用石膏改酸；无排水不要大剂量石膏。",
  "High pH, smears wet and sets hard dry, poor emergence — that looks sodic. Gypsum is for alkali, not every white crust.","Gypsum’s calcium swaps sodium, then water must wash sodium away. No drainage, wasted gypsum. Salt soils want leaching.","Confirm sodicity with a test. Rate from the test, better too little, small patch, with drainage.","Don’t gypsum an acid soil; don’t high-rate gypsum without an outlet.")
k("sha-tu-lou-fei","一抓就散，雨后很快漏干，肥效短。苗易旱易黄。","沙土是筛子。水肥留不住。一次堆山，第二天就空。","少量多次。有机肥分次拌，覆盖减蒸发。灌溉分顿。氮更要分。","不要按黏土一次把肥倒完；不要指望沙土保得住大水大肥。",
  "It falls apart in the hand, drains in hours, fertiliser is short-lived. Seedlings drought and yellow easily.","Sand is a sieve. Water and nutrients don’t stay. A mountain today is empty tomorrow.","Little and often. Split organic matter, mulch, split irrigation, split nitrogen especially.","Don’t pour a clay-sized dressing in one go; don’t expect sand to hold a flood of water and fertiliser.")
k("nian-tu-nan-geng","湿时黏锄，干时大块龟裂扯根。宜耕期短。","黏土颗粒细，水一多就糊，水一少就砖。有机质和适墒是钥匙。","适墒才耕。有机肥、秸秆、覆盖改善。不要湿耕和干耕两个极端。","不要雨后马上旋；不要干裂时硬打坷垃当深松。",
  "Sticky when wet, cloddy and cracked when dry, roots torn. The tillage window is short.","Fine particles paste when wet and brick when dry. Organic matter and crumb-moist timing are the keys.","Till only at crumb-moist. Organic matter, straw, cover. Avoid both wet smearing and dry pulverising.","Don’t rotary-till after rain; don’t smash dry clods and call it subsoiling.")
k("li-di-ceng","剖面 15～20 厘米以下一层发亮硬盖，根到那儿拐弯。上层雨后积水。","同一深度年年旋、湿土进机，压出犁底层。根浅了，旱涝都更敏感。","隔年深松超过硬盖。适墒。有机质跟上。不要年年翻生土。","不要只旋十几厘米又压实；湿土不要进重车。",
  "A shiny hard layer below 15–20 cm; roots turn. The top ponds after rain.","The same rotary depth every year, plus wet traffic, irons a pan. Shallow roots then fear both drought and flood.","Subsoil in alternate years just through the pan, crumb-moist, with organic matter. Don’t invert raw subsoil yearly.","Don’t fluff 15 cm and pack it again; keep heavy traffic off wet soil.")
k("hei-tu-tui-hua","黑土层变薄，心土露出，土色发灰发硬。不是记忆里又黑又肥的那层。","黑土的肉在有机质。风蚀、水蚀、只拿不还，黑土层一年年变薄。加氮补不回变薄的 A 层。","秸秆还田、少裸露、坡地覆盖、轮耕。有机肥养肉。产量目标不要把土吃空。","不要把退化黑土当无底洞加氮；不要坡地冬春裸露。",
  "The black layer thins, subsoil shows, colour greys and hardens. Not the fat black you remember.","The meat of black soil is organic matter. Wind, water, take-and-not-return thin the A horizon. Extra nitrogen does not grow that layer back.","Keep straw, less bare ground, cover slopes, rotate tillage, organic matter as meat. Don’t eat the soil for a yield target.","Don’t treat thinning black soil as a nitrogen pit; don’t leave slopes bare in winter-spring.")
k("jie-gan-huan-tian","还田后出苗黄弱、粉碎压实不够也会出苗难。土发热、抢氮。","秸秆碳多，微生物先吃饭，苗会饿一阵。碎得不够、压不实，出苗像钻被子。","粉碎、抛匀、压实。按农技站补几公斤量级氮把账还上。墒情好再播。","不要整段秸秆盖种；不要不补氮又按原计划密播。",
  "After return, seedlings yellow and weak; coarse unpressed straw also blocks emergence. The soil runs a fever and borrows nitrogen.","Straw is carbon-rich. Microbes eat first and seedlings go hungry. Coarse, unpressed straw is a quilt the seedling cannot pierce.","Chop, spread, press. A few kg nitrogen/mu class via extension to pay the IOU. Sow into moisture.","Don’t sow under long straw; don’t skip the nitrogen IOU and still plant at full density.")
k("shi-hui-yong-liang","已经决定改酸，问题变成用哪种灰、撒多少、何时撒。看包装。","农用石灰改酸，白云石带镁，生石灰劲猛伤苗。沙土少、黏土略多，分两次。铵态氮隔 7～10 天。","认包装。按质地取区间下限，分两次旋进。与尿素鲜粪错开一周。下一季再测，过了目标就停。","生石灰不往苗上撒；不要建筑石灰当农用石灰；不要和尿素同一天混。",
  "You already decided to lime. Now: which lime, how much, when. Read the bag.","Agricultural lime for acid, dolomite brings magnesium, quicklime is harsh on seedlings. Sand less, clay a little more, split. Keep 7–10 days from ammonium-N.","Read the bag. Take the floor of the range by texture, split, work in. Keep a week from urea and fresh manure. Retest next season; stop at the target.","No quicklime on seedlings; no builder’s lime as farm lime; no mix with urea the same day.")
k("xiu-shui-tian","水面锈、有时油膜，稻苗黄僵，根发黑。不是旱地玉米那套。","还原条件下亚铁出来毒根。长期深水、酸、有机质发酵会叠。","排水露田给根空气。测 pH。酸则按改酸文少量。新根出来再薄肥。","不要锈水田当缺氮猛尿素；不要长期深水不晒。",
  "Rusty water, sometimes an oil film, rice yellow and stalled, roots black. Not a dryland maize story.","Under reduction, ferrous iron poisons roots. Long deep water, acid and fermenting organic matter stack.","Drain and expose soil for air. Test pH. If acid, lime a little per the acid guide. Thin feed only after new roots.","Don’t treat rusty water as nitrogen hunger; don’t keep deep water without an airing.")
k("qian-yu-tian","土冷、长期渍水、剖面发青灰。春季不发苗。山垄冷浸田典型。","潜育层缺氧又冷。根不往下，肥再多也吃得慢。","开沟排水、水旱轮作、增温。磷肥集中施在根旁。不要一僵就猛氮。","不要冷浸田当单纯缺肥；不要堵住排水种一季。",
  "Cold soil, long saturation, a grey-blue layer. Spring seedlings sit. Mountain-cold paddies are the type.","A gley layer is both airless and cold. Roots won’t go down; extra fertiliser is eaten slowly.","Ditch, drain, rotate wet-dry, warm the soil. Band phosphorus by the root. Don’t pour nitrogen at the first stall.","Don’t treat a cold gley as simple hunger; don’t block drains for one crop.")
k("shui-tian-huan-yuan","长期深水，土发臭，根黑不发新根，有时有硫化氢味。","氧气没了，锰铁硫被还原，根被毒。不是缺那一袋复合肥。","晒田、排深水、等新根。测 pH。有机肥要用腐熟的，不要鲜草沤在深水里。","不要根黑时加倍施肥；不要长期不晒田。",
  "Long deep water, soil smells, roots black with no new white tips, sometimes a hydrogen-sulphide smell.","No oxygen, manganese iron and sulphur reduce, roots are poisoned. Not a missing bag of compound.","Dry the field, drop deep water, wait for new roots. Test pH. Organic matter must be rotted — don’t steep fresh herbage in deep water.","Don’t double fertiliser on black roots; don’t skip aeration year after year.")
k("gen-fu-jian-bie","点片死棵先看根。黑腐、根结、茎基缢缩，和缺肥的白根细弱不是一路。","肥解决不了烂根。土问题可以叠病害，但切开维管束、闻气味、看分布，能先分流。","拔病株和健株对照。点片加褐根走病害路径，问农技站植保。全田匀黄走缺素或涝。这里不开药方。","不要点片死棵还当缺肥猛追；不要病根上再灌浓肥。",
  "Patch death: look at the root first. Black rot, knots, pinched stem bases are not the thin white roots of hunger.","Fertiliser will not cure a rotten root. Soil problems can sit with disease, but a cut stem, a smell and the pattern split the road.","Pull a bad plant and a good one. Patch plus brown roots go to plant protection. Uniform yellow goes to nutrient or wet. No pesticide recipes here.","Don’t chase patch death with fertiliser; don’t drench a rotten root with strong feed.")
k("huang-ye-jian-bie","先分新叶还是老叶，再分匀黄还是脉间黄，再问药、涝、病。一张黄叶不够下肥。","老叶匀黄像缺氮；新叶脉绿像缺铁；斑扭来得快像药害；湿蔫像涝。叶位是第一把尺子。","拍三张：全株、叶背、土面。对照邻行。拿不准测土或拍照问。不要按最贵的叶面肥先喷。","不要见黄就尿素；不要四种黄叶用同一瓶微肥。",
  "Split new versus old leaves, uniform versus interveinal, then ask spray, wet, disease. One yellow leaf is not a fertiliser order.","Old-leaf uniform yellow looks like nitrogen; new-leaf green veins like iron; fast twist like pesticide; wet wilt like waterlogging. Leaf position is the first ruler.","Three photos: whole plant, leaf back, soil surface. Compare the next row. Unsure: test or ask with a photo. Don’t spray the dearest foliar first.","Don’t greet every yellow with urea; don’t treat four yellows with one micronutrient bottle.")
k("han-yan-jian-bie","一边萎蔫无白霜土干，一边白霜加焦边土不一定干。先分土是干还是湿、白不白。","旱是没水，咸是有水喝不着。浇小水：旱了能缓，咸了有时更蔫。","抓一把土。干、白、有霜走盐；干、无霜、浇了能缓走旱。再测 EC 更稳。","不要旱了当咸洗盐；不要咸了当旱猛浇小水。",
  "One side wilts with no frost and dry soil; the other has frost plus scorch and soil that may still be moist. Dry versus wet, white versus not.","Drought is no water. Salt is water the root cannot drink. A small drink: drought eases, salt may wilt more.","Grab a handful. Dry, white, frosted → salt. Dry, no frost, eases after water → drought. EC makes it safer.","Don’t leach a drought; don’t sip-irrigate a salt crust.")
k("cha-yuan-guo-suan","茶树还活着但叶小、新梢短、根色差。茶园单独取样，不要和粮田混。","茶树能喝酸，不等于拿醋当水。适宜大约 pH 4.5～6.0。低于 4.0 根一样伤。","茶园单独测 pH。4.5～6.0 先养有机质。低于 4.0 才极少量农用石灰。不用生石灰。","不要按粮田改到 6.5～7；不要过酸不测就当缺肥。",
  "The bush lives but leaves are small, shoots short, roots poor. Sample the tea row alone, not mixed with grain.","Tea can drink acid; it does not want vinegar as water. About pH 4.5–6.0. Below 4.0 roots still hurt.","Test tea pH alone. Between 4.5 and 6.0, grow organic matter. Below 4.0, a little agricultural lime. No quicklime.","Don’t push tea to 6.5–7 like grain; don’t treat extra-acid as hunger without a test.")
k("ma-ling-shu-tu","块茎皮上疮痂，不是土面。偏碱偏干沙地更常见。","疮痂喜欢偏碱、干、沙。把 pH 改酸一点、稳墒，比打药故事实在。这里不开杀菌剂方。","测 pH。偏碱不要再加石灰。稳墒，轮作。品种问农技站。","不要疮痂田再撒石灰；不要只当病害打药不问 pH。",
  "Scab is on the tuber skin, not the soil surface. Worse on alkaline, dry, sandy ground.","Scab likes alkaline, dry sand. A little more acid and even moisture beat a spray story. No fungicide recipes here.","Test pH. Don’t lime an already alkaline potato field. Even moisture, rotate. Cultivar via extension.","Don’t lime a scab field; don’t spray and ignore pH.")
k("sheng-wu-you-ji-fei","袋上写菌，土还是板、咸、没肉。倒完一季看不出房。","菌是房客。没房没饭，安慰剂。先有有机质和通气，菌才住得下。看登记证。","先改房改饭：有机质、通气、pH 和盐在活区间。菌剂按标签，小面积。不要当唯一修理。","不要菌和杀菌剂一起倒；不要不改土只倒菌。",
  "The bag says microbes; the soil is still hard, salty, thin. One season later the house is unchanged.","Microbes are tenants. No house, no meal — a placebo. Organic matter and air first. Read the registration.","Fix the house: organic matter, air, pH and salt in a living range. Product on the label, small patch. Not the only repair.","Don’t mix with a sterilant; don’t skip soil repair and only pour microbes.")
k("guo-yuan-tu-rang","树下那层土板、清耕、草都没有。新梢短，肥效飘。","果树吃的是树盘。清耕把肉晒掉。行间生草、树盘覆盖、肥进根区，才像养树。","树盘覆盖或生草。腐熟有机肥沟施到根区。氮不要全撒在地表。滴灌把水肥送到根。","不要清耕把树盘裸着晒；不要肥撒在行间人走的地方。",
  "Soil under the tree is hard, clean-cultivated, no cover. Shoots short, fertiliser ‘evaporates’.","A fruit tree eats the tree row. Clean cultivation bakes the meat. Cover, grassed alleys, fertiliser in the root zone.","Mulch or grass the row. Rotted organic matter in a root-zone trench. Don’t throw all nitrogen on the surface. Put drip in the roots.","Don’t bake a bare tree row; don’t fertilise the walkway.")
k("da-peng-lian-zuo-zong-he","棚内盐斑加病株，越种死棵越多。不是单一缺肥。","盐、病、肥害熬在一口锅里。一瓶药一袋肥掀不开这口锅。先测 EC，再看根。","测 EC。能洗先洗。看根结根腐走植保。轮作或基质是后面的牌。改水肥习惯。","不要只补肥；不要不测 EC 就翻棚。",
  "Salt patches plus sick plants in the house; more death each year. Not one missing nutrient.","Salt, disease and burn stew in one pot. One bottle and one bag will not un-stew it. Test EC, then the root.","Test EC. Leach if you can. Knots and rot go to plant protection. Rotation or substrate later. Change the water-fertiliser habit.","Don’t only feed; don’t strip the house without an EC.")
k("hong-huang-rang-gai-suan","红土黄泥土上苗僵叶黄根褐，先认土色和根，再认 pH。","红黄壤本底就酸，雨把盐基淋走。石灰是药不是饭。","0～20 厘米 pH 不到 5.5 才改，沙土按下限分两次，配有机肥，明年再测。","不要按北方麦田石灰账抄；茶园不要套粮田区间。",
  "On red-yellow earth, stunted yellow plants with brown tips — read colour and roots, then pH.","The soil is already acid; rain strips bases. Lime is medicine, not a meal.","Lime only below pH 5.5 at 0–20 cm, sand at the floor, split, with organic matter, retest next year.","Don’t copy a northern wheat lime rate; don’t use grain rates on tea.")
k("lv-du-shang-gen","根尖像被烫过，发褐、秃、不伸；叶子再追氮也不发棵。","酸到一定程度，铝从土粒上掉下来咬根尖。根被咬了，肥再多也吃不进。","洗根看尖，测 pH。少量分次农用石灰降铝。先让新根出来再薄肥。有机质能络合一部分铝。","根秃时不要猛尿素；不要不测当缺肥加倍。",
  "Root tips look scalded, brown, bald, not stretching; extra nitrogen still won’t grow a canopy.","When soil is acid enough, aluminium comes off the clay and bites tips. A bitten root cannot eat fertiliser.","Wash tips, test pH. A little split lime to drop aluminium. New roots first, then a thin feed. Organic matter can bind some aluminium.","Don’t pour urea on bald roots; don’t treat it as hunger without a test.")
k("suan-yu-que-gai","番茄脐腐、裂果、心叶焦边，喷叶面钙只能救急。","酸土里钙被淋走。钙像砖，干旱时根更吃不到。叶面钙退烧，改土才是正道。","测 pH 和交换性钙。酸则少量石灰质。浇水均匀。叶面钙按包装喷幼果，先小面积。铵态氮先降。","不要只打叶面钙不改酸；缺钙时不要猛冲尿素。",
  "Blossom-end rot, split fruit, scorched heart leaves — a calcium spray is only a rescue.","Acid soil leaches calcium. Calcium is a brick; drought makes the root miss it. Foliar calcium lowers the fever; the soil job remains.","Test pH and exchangeable calcium. A little lime if acid. Even water. Foliar calcium on young fruit at the label, small patch. Drop ammonium-N.","Don’t live on foliar calcium; don’t chase the rot with urea.")
k("suan-tu-shi-lin","苗紫、矮、根少，不一定土里没磷。酸土里铁铝把磷钉死。","你撒的过磷酸钙，根摸不着。先把锁打开，再谈用量。","测 pH 和有效磷。过酸先少量石灰。磷肥条施穴施在根旁。苗期叶面磷酸二氢钾按说明救急。","不要不改酸就把磷肥当饭猛倒；不要石灰和磷肥同一天混堆。",
  "Purple, short, few roots — not always ‘no phosphorus in the soil’. Acid iron and aluminium nail P down.","The superphosphate you threw is out of the root’s reach. Open the lock, then talk rate.","Test pH and available P. A little lime if too acid. Band P by the root. Foliar potassium dihydrogen phosphate as a labelled rescue.","Don’t pour P as a meal without opening the lock; don’t heap lime and phosphate the same day.")
k("sheng-li-suan-xing-fei","连年高产田渐渐发僵，pH 一年年往下掉。翻近几年氮钾肥包装。","有的肥进了土，作物吃走阳离子，留下酸根。不是肥有毒，是账要会算。","氮肥种类轮换，配腐熟有机肥。过酸按改酸文处理。不要靠年年加大石灰去顶酸性肥。","不要用石灰去抵消不合理的过量氮；不要不测 pH 年年加氮。",
  "A high-yield field slowly stalls; pH walks down year after year. Read the last years of N and K bags.","Some fertilisers leave an acid tail after the crop takes the cation. Not poison — bookkeeping.","Rotate N forms, add rotted organic matter. If too acid, follow the acid guide. Don’t lime every year to cancel acid-forming fertiliser.","Don’t lime to offset a foolish nitrogen habit; don’t add N every year without a pH.")
k("cha-yuan-shi-hui-jin-ji","茶树新梢短、叶小；有人照搬粮田石灰，随后更黄。茶园窗口大约 4.5～6.0。","茶树是耐酸的人，不是喜欢喝石灰水。过酸降一点铝，过碱又把铁锁住。","先测 pH。过低才少量石灰质，用量远低于粮田上限，分次。增有机肥覆盖。","不要按粮田亩施 150 公斤起步；不要把茶园 pH 改到 7；不要石灰撒在茶丛根颈上。",
  "Tea shoots short, leaves small; someone copied grain lime and it yellowed more. Tea’s window is about 4.5–6.0.","Tea tolerates acid; it does not drink limewater. Too acid, drop a little aluminium; too alkaline, iron locks.","Test pH. Only if too low, a little lime far below grain maxima, split. Organic matter and cover.","Don’t start at 150 kg/mu like grain; don’t push tea to pH 7; don’t throw lime on the collar.")
k("su-da-yan-jian","土发涩发黏，pH 常大于 8.5，结构差，苗出不来。不一定有很厚白霜。","盐是汤咸，碱是汤涩还挂碗。石膏里的钙把钠换下来，再靠水把钠洗走。","化验确认碱化再考虑石膏。必须有排水。配有机肥和耐碱作物。先小片。","不要把盐土当碱土猛撒石膏；不要给酸土用石膏改酸。",
  "Soil feels soapy and sticky, pH often above 8.5, structure gone, poor emergence. A thick frost is not required.","Salt is salty soup; alkali is soapy soup that coats the bowl. Gypsum’s calcium swaps sodium, then water must wash it away.","Confirm sodicity, then gypsum, with drainage, organic matter and tolerant crops. Small patch.","Don’t gypsum a chloride salt soil by default; don’t gypsum an acid soil.")
k("bin-hai-yan-tu","春季返盐白霜、出苗花斑，靠近海或倒灌河。先问排水沟通不通。","海退了盐还在。洗盐像洗衣，要有进水也要有出水。没有排水，大水只是把盐赶到田边。","开挖疏通排沟。有灌有排才洗。覆盖减蒸发。先种耐盐作物。肥要淡。","不要无排水灌大水；不要盐斑上猛施复合肥。",
  "Spring frost, patchy emergence, near the sea or a tidal river. Ask whether the ditch actually runs.","The sea left; the salt stayed. Leaching is laundry — in and out. No outlet, flooding parks salt on the edge.","Open the ditch. Leach only with an outlet. Mulch. Salt-tolerant crops first. Dilute fertiliser.","Don’t flood without drainage; don’t throw compound on the salt patch.")
k("wei-xian-shui-guan-gai","浇了几次苗更焦边、土面更白。问井水渠水是否发涩发咸。","微咸水不是不能用，是不能当自来水天天喝。小水勤浇最容易返盐。","测灌溉水 EC。能轮灌淡水就轮。灌就灌透并排出。覆盖。苗期尽量用更淡的水。","不要微咸水小水勤浇；不要苗期只用咸水。",
  "After a few irrigations, margins worse and the surface whiter. Ask whether the well or canal tastes brackish.","Slightly saline water is usable, not as daily tap water. Small frequent drinks raise salt most.","Test water EC. Alternate with fresh if you can. Irrigate through and drain. Mulch. Fresher water at seedling.","Don’t sip-irrigate with brackish water; don’t use only saline water on seedlings.")
k("di-biao-fu-yan","膜边、破孔周围一圈白霜，苗出在孔边就焦。膜内土壤可能还湿。","膜是帽子。帽子挡住蒸发，盐就从帽檐爬出来。苗要坐在帽子底下的湿润区。","播种避开盐圈。灌水要灌到膜内湿润峰。适时破膜放苗、中耕。有排水的洗一次。","不要只在膜边浇一小水；不要盐圈上补苗又补肥。",
  "A white ring at the film edge and hole; seedlings there scorch. Soil under the film may still be moist.","Film is a hat. It stops evaporation, so salt queues at the brim. Sit the seedling in the wet bulb under the hat.","Sow off the salt ring. Irrigate the wet bulb inside the film. Cut the film and cultivate on time. Leach if you can drain.","Don’t sip-water the film edge; don’t replant and refertilise the salt ring.")
k("yan-jian-di-xuan-zuo","年年缺苗断垄，种玉米像赌博。边上耐盐作物却能出苗。","盐碱地像浅水，先学游泳再比速度。耐盐作物和品种比复合肥堆出来的高产方案实在。","向农技站要耐盐品种。轻度先保苗覆盖。中重度先耐盐作物或牧草。密度宁稀勿密，肥要淡。","不要按邻县高产密度硬套；不要重盐斑上种不耐盐的菜。",
  "Year after year, missing plants; maize is a gamble. A salt-tolerant neighbour still stands.","Salt land is shallow water: learn to swim before you race. Tolerant crops beat a high-yield compound recipe.","Ask extension for tolerant cultivars. Light salt: stand and mulch. Heavy: tolerant crops or grass first. Thinner stands, dilute fertiliser.","Don’t paste a neighbour’s density; don’t plant sensitive vegetables on a heavy patch.")
k("xi-yan-pai-shui","灌了大水，田边更白、邻地开始返盐；地下水变浅。沟口要看出水。","洗衣要拧出去。洗盐不排水，就是衣服在盆里泡着。水是电梯，盐是乘客，没出口就上楼。","清淤田间沟和骨干沟。按当地定额灌并排出。洗后中耕覆盖。水位高的先降。","不要堵着沟灌大水；不要把咸水排到没有出路的邻田。",
  "After a big irrigation the edge is whiter, the neighbour starts to frost, the water table rises. The ditch mouth must run.","Laundry must be wrung. Leaching without drainage is clothes soaking in the basin. Water is the lift; salt is the passenger.","Clear field and main ditches. Irrigate to the local quota and let it out. Cultivate and mulch after. Drop a high water table first.","Don’t flood against a blocked ditch; don’t dump brine onto a neighbour with no outlet.")
k("da-peng-huan-tu-xi-yan","膜下白霜、越浇越蔫。有人建议把土全换掉。先拿电导仪。","大棚是盆。盆里的盐洗得掉就先洗。换土不改习惯，新土很快又咸。换土留给病土或洗不动的盐。","先测 EC。能揭膜淋雨或灌排洗盐就先做。停高盐肥。换土是最后选项，换完必须改水肥。","不要 EC 没测就翻棚；不要换土后仍按老方子猛肥。",
  "Frost under film, more wilt after watering. Someone wants the soil hauled out. Start with an EC meter.","A house is a bowl. If salt will wash, wash. New soil plus old habits is salt again. Replacement is for disease or unleachable salt.","Test EC. Rain or leach first. Stop high-salt fertiliser. Replacement is last, and the habit must change.","Don’t strip the house without EC; don’t refill and keep the old recipe.")
k("xuan-geng-bian-qian","耕层越来越浅，雨后上层积水，刨开看见发亮的一层。根横着走。","旋耕像剃头，只刮表层。年年同一深度，下面压出硬盖。","隔年深松，深度超过旋耕层。避免泥里开拖拉机。秸秆和有机肥让松过的土有肉。","不要每年把生土翻上来晒死；不要湿土旋耕压出泥条。",
  "The tilled layer shallows; the top ponds; a shiny layer appears when you dig. Roots turn.","Rotary tillage is a haircut of the top. The same depth every year irons a pan below.","Subsoil in alternate years deeper than the rotary layer. Keep off mud. Straw and organic matter give the loosened soil meat.","Don’t invert raw subsoil every year to bake it; don’t smear wet soil into ribbons.")
k("shen-song-shi-ji","准备深松却赶上泥地或干硬地；松完大坷垃，苗更差。","手握成团落地能散，就是窗口。深度以刚过硬盖为准，常见 25～40 厘米。过湿是和泥，过干是打坷垃。","适墒、隔年、刚过硬盖。松完要有有机质和覆盖。问农机手是松还是翻。","不要年年深松把生土翻乱；不要泥里作业。",
  "You meant to subsoil into mud or brick; afterwards, clods, worse seedlings.","A handful that holds then falls apart is the window. Depth is just through the pan, often 25–40 cm. Too wet is paste; too dry is bricks.","Crumb-moist, alternate years, just through the pan. Organic matter and cover after. Ask whether the machine rips or inverts.","Don’t subsoil every year and scramble raw subsoil; don’t work mud.")
k("tu-rang-tuan-ju-ti","干了面、湿了浆，一碰就散，雨点一砸就糊。搓不出团粒。","好土像面包，粉土像面粉。团聚体是房间。有机质、覆盖、少碾，房间才在。","有机肥、覆盖防雨点砸、适墒才进地。菌剂一季建不起房间。","不要湿田进车把团粒碾成饼；不要指望一袋菌把面粉变成面包。",
  "Dust when dry, slurry when wet, falls apart, raindrops paste it. You cannot roll crumbs.","Good soil is bread; powder soil is flour. Aggregates are rooms. Organic matter, cover, less traffic build rooms.","Organic matter, cover against raindrop smash, traffic only at crumb-moist. A microbe bag will not build rooms in one season.","Don’t smash crumbs into pancakes on wet soil; don’t expect a bag to turn flour into bread.")
k("ji-ya-che-zhe","车辙里不出苗，垄上有苗。轮胎印是一条死土。","湿土承载差。一次碾压，孔隙塌了，几年缓不过来。固定车道比满田碾体面。","湿田不进车。能固定车道就固定。收获后适墒松辙。不要在辙里补种又补肥。","不要雨后进重车；不要把辙当苗床。",
  "Nothing comes up in the rut; the bed still has plants. A tyre print is a strip of dead soil.","Wet soil cannot carry weight. One pass collapses pores for years. Fixed lanes beat roaming.","Keep off wet ground. Fix traffic lanes if you can. Loosen ruts after harvest at crumb-moist. Don’t replant and refertilise the rut.","Don’t take heavy kit in after rain; don’t treat the rut as a seedbed.")
k("ban-jie-yu-gen-xi","根碰到硬盖拐弯，地上部更浅更黄，土更板。互相反馈。","硬土养浅根，浅根更不改土，土更硬。要打断这个圈。","开一条路：适墒深松刚过硬盖。氮不要全堆在地表，让根往下追。有机质跟上。","不要只在地表猛氮；不要松完不给有机质又压实。",
  "Roots hit a pan and turn; the top stays shallow and yellow; the soil hardens further. They feed each other.","Hard soil raises lazy roots; lazy roots don’t repair soil; soil gets harder. Break the loop.","Open a path: subsoil at crumb-moist just through the pan. Don’t dump all nitrogen on the surface — let roots chase it down. Organic matter after.","Don’t only surface-feed nitrogen; don’t rip then pack without organic matter.")
k("fu-gai-gai-zhi-di","覆盖能挡住雨点砸和蒸发，硬盖还在下面。膜是伞，不是镐。","秸秆和地膜是护理，不是深松。犁底层仍要揭。残膜要捡。","覆盖减蒸发、护团聚体。有硬盖仍要隔年深松。选覆盖材料按当地，残膜回收。","不要以为盖上膜硬盖会自己消失；不要残膜留田年年加。",
  "Cover stops raindrop smash and evaporation; the pan is still underneath. Film is an umbrella, not a pickaxe.","Straw and film are nursing, not subsoiling. A pan still needs ripping. Pick up residual film.","Cover against evaporation and to protect crumbs. A pan still wants alternate-year subsoiling. Choose cover locally; recover film.","Don’t wait for film to melt a pan; don’t leave residual film to stack.")
k("lv-fei-fan-ya","鲜草翻下去，苗黄弱，土发热。翻压过晚过厚更明显。","鲜草会发热、会抢氮。花期翻、等几天、补一点氮，才不像憋苗。","大约开花期翻压，撒匀，等一等，按当地补几公斤量级氮。不要整层厚草捂种。","不要鲜草刚翻就密播；不要不补氮又按原计划下种。",
  "Fresh herbage in, seedlings yellow, soil hot. Worse if late and thick.","Fresh green runs a fever and borrows nitrogen. Incorporate around flowering, wait, add a little N.","Turn around flowering, spread even, wait, a few kg N/mu class locally. Don’t smother seed under a thick wet blanket.","Don’t sow thick on freshly turned green; don’t skip the nitrogen IOU.")
k("sheng-wu-tan","炭渣拌进耕层，指望一季翻身。一小把不能让地改命。","炭是架子，不是饭。没有有机质，架子上没肉。先小片试，看登记和来源。","小面积试验。有机肥仍是主食。读标签。不要当神袋。","不要每亩撒一点就当改土完成；不要来路不明的炭当肥料。",
  "Char mixed in, hoping for a one-season turnaround. A pinch will not rewrite the field.","Char is a frame, not a meal. Without organic matter the frame is bare. Trial a patch; read the label and the source.","Small trial. Organic matter remains the meal. Read the label. Not a miracle sack.","Don’t call a pinch a completed repair; don’t treat mystery char as fertiliser.")
k("you-ji-fei-ru-he-xuan","袋上写有机，有的还烫手还臭，有的盐很高。棚里更要问盐。","不是每袋都是肉。看腐熟：不烫、不熏、色暗。看盐。看碳氮比。生的会烧，咸的会腌。","不发热、不呛氨、颜色暗。设施要问盐分。按当地用量，宁少勿多。先小面积。","不要生粪当腐熟；不要棚里不问盐就高量。",
  "The bag says organic; some still burn the hand and stink; some are salty. Houses must ask salt.","Not every bag is meat. Rotted: not hot, not sharp, dark. Check salt. Check C/N. Raw burns; salty pickles.","No heat, no ammonia bite, dark colour. Greenhouse loads need a salt check. Local rate, better too little, small patch.","Don’t call raw dung rotted; don’t high-rate a house without a salt check.")
k("jie-gan-bu-dan","还田后苗黄，像缺氮。微生物先吃饭。","秸秆碳多，菌要氮。苗会饿一阵。补氮是还账，不是加倍追肥。","按秸秆量和农技站，常见每亩几公斤尿素量级把账还上。粉碎压实。","不要把补氮当成当季产量加倍；不要整段秸秆不补氮密播。",
  "After straw return, seedlings yellow like nitrogen lack. Microbes eat first.","Straw is carbon-rich; microbes need nitrogen. Seedlings go hungry. The extra N is an IOU, not a doubled topdressing.","By straw amount and extension, often a few kg urea/mu class to pay the IOU. Chop and press.","Don’t treat the IOU as a yield doubling; don’t sow thick under long straw with no N.")
k("hei-tu-you-ji-zhi-shou-hu","黑土层在变薄。加氮田还在产，肉却在少。","黑的是肉。守住秸秆、少裸露、轮耕，比再加一袋氮实在。产量目标不要把 A 层吃空。","秸秆还田、坡地覆盖、少风蚀窗口裸地。有机肥养肉。隔年深松不要年年翻生土。","不要把变薄的黑土当无底洞加氮；不要冬春坡地裸着。",
  "The black layer is thinning. Nitrogen still buys yield; the meat is leaving.","Black is meat. Keep straw, less bare ground, rotate tillage — more real than another bag of N. Don’t eat the A horizon for a target.","Return straw, cover slopes, less bare ground in the windy window. Organic matter as meat. Subsoil alternate years, don’t invert raw subsoil yearly.","Don’t treat thinning black soil as a nitrogen pit; don’t leave slopes bare in winter-spring.")
k("sha-tu-zeng-you-ji-zhi","沙土漏，一次堆一座粪山，第二天还是筛子。","筛子盛不住山。少量多次，覆盖，分顿肥，才留得住。","腐熟有机肥分次拌。覆盖。灌溉和氮都要分顿。不要一年堆满。","不要按黏土一次把有机肥倒完；不要生粪当量。",
  "Sand leaks. A mountain of dung today is still a sieve tomorrow.","A sieve cannot hold a mountain. Little and often, mulch, split fertiliser.","Split rotted manure, mulch, split irrigation and nitrogen. Don’t dump a year in one day.","Don’t pour a clay-sized organic dressing once; don’t count raw manure as the same thing.")
k("que-xin-yu-lin","玉米花白苗、节间短；化验磷很高、锌却低。","磷和锌排队进同一扇门。磷人多，锌进不去。不是锌袋子买少了那么简单。","看化验单磷和锌两列。过高的磷先停。叶面锌按说明救急。土施锌数年一次。","不要缺锌时再加大磷肥；不要叶面锌加倍。",
  "Maize white-bud, short internodes; the sheet shows high P and low zinc.","P and zinc queue at one door. A crowd of P blocks zinc. Not simply ‘bought too little zinc’.","Read P and zinc together. Stop excess P. Foliar zinc on the label as rescue. Soil zinc once in years.","Don’t raise P when zinc is short; don’t double foliar zinc.")
k("que-peng-hua-er-bu-shi","花开了不结实，也要问花期旱和盐，不能只怪硼。","硼管开花。缺和毒只隔一层纸。旱和盐也会落花。先分流。","先看墒和盐。叶面硼按包装下限分两次。土施按测土宁少勿多。先小面积。","不要硼肥加倍；不要不测土把硼砂当底肥猛撒。",
  "Bloom without fruit — also ask drought and salt at flowering, not only boron.","Boron runs flowering. Deficiency and toxicity are thin. Drought and salt also drop flowers. Split the road first.","Moisture and salt first. Foliar boron at the label floor twice. Soil boron from a test, better too little. Small patch.","Don’t double boron; don’t broadcast borax as base without a test.")
k("qi-zi-huang-hua","柑橘新梢黄化。有的匀、有的一枝一枝、有的根差。三张照片：新梢、全株、根。","三条路：土里铁被锁、根烂了吃不到、系统性病害。路走错，铁喷得越多越耽误。","看新叶脉绿还是斑驳。挖根白还是褐。缺铁路径叶面螯合铁救急。像病害的找植保，这里不开方。","不要一律当缺铁打；不要黄龙病嫌疑还在补铁耽误时间。",
  "Citrus new-flush yellow. Sometimes even, sometimes one limb, sometimes bad roots. Three photos: flush, tree, root.","Three roads: iron locked, roots rotten, a systemic disease. The wrong road wastes time in iron sprays.","Vein-green versus mottling. White roots versus brown. Iron path: chelated foliar rescue. Disease-like: plant protection. No recipes here.","Don’t treat every yellow as iron; don’t spray iron while huanglongbing is on the table.")
k("pu-tao-shi-hui-tu-que-tie","葡萄新梢黄、叶脉绿，土并不瘦。华北西北石灰性土常见。","钥匙在根际 pH 和氧气。叶面铁能绿一阵，土还是那把锁。","叶面螯合铁救急。树盘覆草。腐熟有机肥改根际。避免大水漫灌。磷过高先停。","不要一黄冲尿素；不要高 pH 土猛撒硫酸亚铁当当季解决。",
  "Grape new leaves yellow, veins green, soil not poor. Common on north-west calcareous ground.","The key is root-zone pH and air. Foliar iron greens for a while; the lock remains.","Chelated foliar iron as rescue. Grass mulch in the row. Rotted organic matter. No flood irrigation. Stop excess P.","Don’t chase yellow with urea; don’t dump ferrous sulphate on high pH as a season fix.")
k("hua-sheng-kong-jia","棵子不小，刨开空荚多、仁秕。问结荚期旱不旱。","花生的钙主要靠果针自己吸。果针周围土干、酸、盐，钙走不到。叶面钙帮一点，荚果层更要紧。","结荚期稳墒。酸土按测土少量石灰质。钙肥施在荚果层。盐地先降盐。","不要只喷叶面钙不管墒；不要酸土不测就猛石灰。",
  "The bush looks fine; dig and the pods are empty, kernels thin. Ask whether pegging was dry.","Peanut calcium is drunk by the peg. Dry, acid or salty soil around the peg, calcium never arrives. Foliar calcium helps a little; the pod layer matters more.","Even moisture at pegging. A little lime on acid soil from a test. Calcium in the pod layer. Drop salt first if saline.","Don’t only spray calcium and ignore moisture; don’t lime acid peanut land without a test.")
k("ye-cai-xiao-xing-yuan-su","心叶焦、叶柄裂、新叶黄脉绿，喷一次好像好了，过几天又来。","叶菜像小孩，缺了马上写在脸上。喷叶是退烧药。退完烧还要看土是不是酸、咸、没肉。","先看叶位和土面。叶面按包装下限救急。测 pH、EC、有机质。盐高先洗，下茬改土。","不要把叶面肥当底肥用一辈子；不要浓度加倍。",
  "Heart-leaf scorch, split petioles, new-leaf yellow with green veins; a spray helps, then it returns.","Leafy greens are children — lack writes on the face at once. A spray is aspirin. After the fever, ask whether the soil is acid, salty, thin.","Leaf position and soil surface first. Foliar at the label floor. Test pH, EC, organic matter. Leach if salty. Repair next crop.","Don’t live on the knapsack; don’t double the concentration.")
k("shui-dao-jiang-miao","返青后不发棵。可能冷浸、亚铁毒、酸、缺磷、种肥烧。先看水温、锈水、根色。","僵苗是一组症，不是一个缺。冷要增温排水，锈水要排，酸要测 pH，肥害沿施肥沟。","看水温和土温。看锈水油膜。洗根：白、黑、褐。分流后再薄肥，根黑时不要猛氮。","不要一律当缺氮猛尿素；不要根黑时加倍复合肥。",
  "After green-up the rice sits. Cold, ferrous toxicity, acid, low P, seed-furrow burn — split them. Water temperature, rusty water, root colour first.","Stall is a family, not one lack. Cold wants warmth and drainage; rust wants drainage; acid wants pH; burn follows the fertiliser band.","Read water and soil temperature. Rust and film. Wash roots white/black/brown. Split, then a thin feed. No heavy N on black roots.","Don’t greet every stall with urea; don’t double compound on black roots.")
k("yu-mi-miao-huang","玉米苗黄要分：下部匀黄像缺氮；条纹失绿像缺锌；扭曲像药害；湿根像涝。","一袋尿素盖不住四条路。叶位、根、土面、喷药史，四样问完再动手。","老叶匀黄走氮路径少量多次。花白苗条纹走锌并问磷。斑扭问药。湿根先排。","不要见黄就尿素；不要四种黄用同一瓶微肥。",
  "Maize seedling yellow splits: old-leaf uniform like N; striping like zinc; twist like herbicide; wet roots like waterlogging.","One urea bag does not cover four roads. Leaf position, root, soil surface, spray history — then act.","Old-leaf yellow: little-and-often N. White-bud stripes: zinc and ask phosphorus. Twist: the spray. Wet roots: drain.","Don’t greet every yellow with urea; don’t treat four yellows with one bottle.")
k("gen-jie-xian-chong","根上长珠子、瘤，肥再多也不长。那些珠子不是根瘤菌。点片萎蔫。","线虫占了根。轮作换科、卫生、抗性砧或品种。用药去农技站按标签，这里不开方。","拔一棵洗根。确认是结不是固氮瘤。轮作、清洁田园。产品走植保。","不要当缺肥猛追；不要病根上灌浓肥。",
  "Beads and galls on roots; extra fertiliser won’t grow. Those pearls are not rhizobia. Patch wilt.","Nematodes occupy the root. Rotate family, hygiene, resistant stock. Products via extension and the label — no recipes here.","Pull and wash a plant. Confirm galls, not nodules. Rotate, clean the field. Products via plant protection.","Don’t chase it with fertiliser; don’t drench galled roots with strong feed.")
k("tu-chuan-ku-wei","点片死棵，切开茎维管束发褐。不是单纯旱。","褐管子是土传萎蔫的名片。轮作、嫁接、卫生。确诊走农技站。这里不开药方。","对照健株。点片加褐管走病害路径。轮作换科。棚内还要问盐。","不要当干旱猛浇；不要病株留田。",
  "Patch death; brown vascular tissue in a cut stem. Not simple drought.","Brown pipes are the name card of soil-borne wilt. Rotate, graft, hygiene. Confirm with extension. No pesticide recipes here.","Compare a healthy plant. Patch plus brown pipes go to disease. Rotate family. In houses, ask salt too.","Don’t flood it as drought; don’t leave dead plants in the field.")
k("qing-ku-bing-tu","热天茄科整株突然萎，切茎有时能挤出菌脓。来得快。","青枯是土里的细菌性萎蔫。闷棚能压一部分，不是万能开关。轮作、排水、抗性品种。","热季萎蔫加乳状菌脓走这条路。轮作排水。闷棚按规程，消完要养。确诊植保。","不要把闷棚当永久疫苗；不要病土连作再毒一次了事。",
  "Hot-weather solanums collapse overnight; a cut stem may ooze. Fast.","Bacterial wilt lives in soil. Solarisation knocks some, not a magic switch. Rotate, drain, resistant cultivars.","Hot-season collapse plus milky ooze. Rotate and drain. Solarise to spec, then nurse the soil. Confirm with plant protection.","Don’t treat solarisation as a forever vaccine; don’t disinfect and replant the same host as the whole plan.")
k("cao-mei-lian-zuo","草莓棚第五年，盐、线虫、黄萎挤在一起。死棵加白霜。","年五很少是一个原因。读 EC、根结、维管束。洗盐、轮作或改基质。不要只喂。","测 EC。洗根看结。切开维管束。能洗先洗。轮作或基质。改水肥。","不要只补肥；不要不分流就一瓶药打到底。",
  "Year five in a strawberry house: salt, nematode, wilt together. Death plus frost.","Year five is rarely one cause. Read EC, knots, vasculars. Leach, rotate, or move to substrate. Don’t only feed.","Test EC. Wash roots for knots. Cut vasculars. Leach if you can. Rotate or substrate. Change the feed.","Don’t only fertilise; don’t one-bottle the stew without splitting the road.")
k("ping-guo-zai-zhi","挖了老树坑再栽，还是那坑土。新树弱，根不扩展。","再植障碍在土里：残根、病菌、偏肥、结构。换坑不换土，故事没完。","尽量换位置。客土或基质。腐熟有机肥改根区。不要老坑原肥原水。","不要在老坑用老方子；不要把残根留在新根区。",
  "The old tree is gone; the same pit remains. The new tree stays weak, roots don’t explore.","Replant trouble lives in the soil: old roots, pathogens, lopsided fertiliser, structure. A new tree in old dirt is the same story.","Move the station if you can. Fresh soil or substrate. Rotted organic matter in the root zone. Don’t reuse the old water-fertiliser recipe.","Don’t plant the old pit with the old recipe; don’t leave old roots in the new root zone.")
k("gao-wen-men-peng","薄膜盖土，能压菌，也会伤结构和有益生物。闷完土更板更臭也常见。","闷棚是药，不是饭。消完要养：有机质、通气、有时要补菌的房和饭。连作再毒，病菌会回来。","按规程闷。闷完养土，不要立刻密植原茬。轮作更稳。","不要把闷棚当永久疫苗；不要闷完接着连作再毒。",
  "Film on soil can knock pathogens; it also hurts structure and the living. Afterwards, harder, smellier soil is common.","Solarisation is medicine, not a meal. After it, nurse: organic matter, air, a house for biology. Disinfect and replant the same host, and they return.","Solarise to spec. Nurse afterwards; don’t immediately replant the same crop dense. Rotation is safer.","Don’t treat solarisation as a forever vaccine; don’t disinfect, replant, disinfect as the whole plan.")
k("han-lao-ji-zhuan","刚涝过又干裂，苗先蔫后黄。根来不及换气。","旱涝急转先伤根。根伤了再黄叶，不要只看叶色下肥。","先排水再谈浇。等新根。叶面薄肥过渡。破托水的犁底层。","不要土湿当旱浇；不要涝后立刻猛氮。",
  "Flood then crack; seedlings wilt then yellow. Roots had no time to breathe.","Drought-flood shock hurts roots first. Yellow leaves come after. Don’t read only the leaf for a fertiliser order.","Drain before you irrigate. Wait for new roots. Thin foliar as a bridge. Break a perched pan.","Don’t irrigate wet soil as drought; don’t dump nitrogen the day after a flood.")
k("di-xia-shui-wei-gao","土坑里很快渗出水。土面看着干，底下在憋。根扎不深。","水位高，氧气少，根不敢往下。旱涝都更敏感。先降水位，再谈深施肥。","开沟降。选浅根作物过渡。不要把所有肥都送到灌不下去的深层。","不要水位高还深松成沟槽蓄脏水；不要当干旱猛浇。",
  "A pit weeps water in minutes. The surface looks dry; underneath it is drowning. Roots stay shallow.","A high water table means little air; roots won’t go down. Both drought and flood then hurt more. Drop the table before you deep-place fertiliser.","Ditch and drop. Use a shallow-rooted crop as a bridge. Don’t send all fertiliser to a depth that stays drowned.","Don’t subsoil a high table into a dirty-water trench; don’t irrigate it as drought.")
k("yu-hou-ban-jie-kai-lie","雨后玉米卡在硬壳里。土面龟裂，跑墒又卡苗。","雨点砸实，太阳一晒就成锅盖。粉土、无覆盖、雨后进车更重。","雨后能进地时浅中耕破壳。覆盖减少下一次砸实。有机质改善。","不要雨后马上旋成泥条；不要干裂时硬打坷垃伤苗。",
  "After rain, maize is stuck under a crust. The surface cracks, moisture runs, seedlings jam.","Raindrops smash, sun bakes a lid. Powder soils, no cover, traffic after rain make it worse.","When you can enter, a shallow cultivation breaks the lid. Cover against the next smash. Organic matter helps.","Don’t rotary-till into ribbons after rain; don’t smash dry crust into the seedlings.")
k("leng-shui-guan-miao","进水口一条黄僵苗，邻行更绿。冷水灌苗，不是整田缺肥。","冷水打在苗上，根停。水口一条，不像全田缺素那么匀。","调进水，避免清晨冰水直灌苗。水口改道或缓一缓。确认后再薄肥。","不要水口黄苗当全田缺氮猛追；不要冷晨灌苗。",
  "A yellow stalled strip at the inlet; the next rows are greener. Cold water on seedlings, not a whole-field hunger.","Cold water hits seedlings and roots stop. A strip at the inlet is not the even yellow of a field-wide deficiency.","Change the inlet. Don’t pour icy dawn water on seedlings. Reroute or pause. Thin feed only after you know.","Don’t treat the inlet strip as field-wide nitrogen; don’t irrigate seedlings with dawn-cold water.")
k("yan-jiang-qi-hou-tu","沿江稻田水冷苗黄。铲上一锹青灰色，有锈斑。潜育化比表面看起来更狠。","灰蓝土、锈斑，根不爱往下。表面看着像普通水田，底下在憋。","开沟排水。水旱轮作。增温。磷集中在根旁。不要只看叶色下氮。","不要沿江冷浸当普通缺肥；不要堵住排水。",
  "Riverside paddies, cold water, yellow seedlings. A spade of grey-blue with rust mottles. Gley is harsher than the surface looks.","Grey-blue soil, rust mottles, roots won’t go down. The surface looks like a normal paddy; underneath it is drowning.","Ditch and drain. Wet-dry rotation. Warm the soil. Band P by the root. Don’t read only the leaf for nitrogen.","Don’t treat riverside gley as ordinary hunger; don’t block drains.")
k("shui-fei-yi-ti-hua-ec","滴口白圈，越浇越蔫。EC 超了就是在腌根。","水肥一体化不是越浓越有劲。苗期更严。没有仪器就送水样。","测水和土 EC。降浓度，灌透把盐推开。按作物耐盐，苗期更淡。先小面积调方。","不要 EC 超了还加浓；不要滴口白圈上再加肥。",
  "A white ring at the dripper, more wilt after a shot. Over-EC is pickling the root.","Integrated water-fertiliser is not ‘stronger is better’. Seedlings are stricter. No meter: send a water sample.","Test water and soil EC. Drop the recipe, irrigate through to move salt. Crop tolerance, seedlings more dilute. Adjust on a small patch.","Don’t concentrate further past EC; don’t fertilise the white ring.")
k("ji-zhi-yu-tu-rang","基质袋栽和土栽在一个棚，方子却常被抄错。基质没有土壤的缓冲，EC 更敏感。","土壤能瞒一点错。基质瞒不住。浇水和配方要按基质走，不能按园土袋数抄。","两套档案。基质更勤测 EC、pH。排液要看。土栽的粪肥习惯不要原样倒进袋。","不要把园土方子倒进椰糠袋；不要基质按土壤那样一次堆肥。",
  "Bags and soil beds in one house; recipes get copied the wrong way. Substrate has no soil buffer; EC is jumpy.","Soil forgives a little. Substrate does not. Water and recipe must follow the substrate, not the garden-soil bag count.","Two files. Test EC and pH more often in substrate. Read the leachate. Don’t pour soil-manure habits into a bag.","Don’t pour a garden-soil recipe into coir; don’t heap manure into substrate as if it were soil.")
k("tu-rang-xiao-du-bian-jie","消完接着连作，病菌会回来。消是药，养是饭。","能压菌，也会伤结构。消完要有机质、通气、有时要给房客重新安家。连作再毒不是策略。","按规程消。消完养土。轮作比连消更稳。产品走标签和农技站。","不要消完立刻密植原茬；不要把消毒当永久疫苗。",
  "Disinfect then replant the same host, and they return. Disinfect is medicine; nursing is the meal.","You can knock pathogens and also hurt structure. Afterwards: organic matter, air, a house for biology. Disinfect-and-repeat is not a strategy.","Disinfect to spec. Nurse afterwards. Rotation beats endless disinfection. Products on the label via extension.","Don’t immediately replant the same crop dense; don’t treat disinfection as a forever vaccine.")
k("jian-yi-ph-ec","地头试纸和电导仪是尺子，不是判决书。土浆要会做。","pH 试纸看酸碱方向，电导仪看咸不咸。数字是区间。极端才优先改。","土水比按说明。试纸比色在光线下。EC 测饱和浸提或按仪器说明。记下点和日期。极端再送实验室。","不要试纸一色就按最大量改土；不要 EC 没校就信一位小数。",
  "Field pH paper and an EC meter are rulers, not verdicts. You must make the paste properly.","Paper shows the acid-alkaline direction; EC shows salt. Numbers are ranges. Extremes get priority.","Soil:water as the note says. Read paper in good light. EC on a saturated paste or as the meter says. Log spot and date. Extremes go to the lab.","Don’t lime at the maximum from one paper colour; don’t trust a decimal on an uncalibrated meter.")
k("shi-fei-tiao-tu-rang","黄叶和化验单对照着看。叶色是线索，化验才是账本。","看叶片能猜，不能代替测土。四种黄叶可能四条路。先分流再下肥。","拍叶位、根、土面。对照化验单。对不上就测，不要按最贵的叶面肥先喷。","不要见黄就尿素；不要用叶色代替取样。",
  "Hold the yellow leaf against the lab sheet. Colour is a clue; the sheet is the ledger.","Leaves let you guess; they do not replace a test. Four yellows can be four roads. Split, then feed.","Photo leaf position, root, soil surface. Compare the sheet. If they disagree, test. Don’t spray the dearest foliar first.","Don’t greet yellow with urea; don’t let leaf colour replace sampling.")
k("nan-fang-shui-tian-yang-fen","南方水田苗黄水冷。长期深水，铁锰起来、养分下去。还原层把养分锁住了。","不是缺那一袋复合肥。先给根空气，养分才会开门。锈水、黑根、臭味是线索。","排水露田。看根色和水。酸则按改酸文。新根出来再薄肥。腐熟有机肥，不要鲜草沤深水。","不要长期深水猛氮；不要黑根时加倍复合肥。",
  "Southern paddies, yellow seedlings, cold water. Long deep water: iron and manganese rise, nutrients lock in the reduced layer.","Not a missing bag of compound. Give roots air and the door opens. Rusty water, black roots, a smell are clues.","Drain and expose. Read roots and water. If acid, follow the acid guide. Thin feed after new roots. Rotted organic matter, not fresh herbage steeped deep.","Don’t keep deep water and pour nitrogen; don’t double compound on black roots.")

