/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as EncyclopediaRouteImport } from './routes/encyclopedia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityIdRouteImport } from './routes/community/$id'
import { Route as CommunityNewRouteImport } from './routes/community/new'
import { Route as EncyclopediaIndexRouteImport } from './routes/encyclopedia/index'
import { Route as EncyclopediaIdRouteImport } from './routes/encyclopedia/$id'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaRoute = EncyclopediaRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityNewRoute = CommunityNewRouteImport.update({
  id: '/community/new',
  path: '/community/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaIndexRoute = EncyclopediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EncyclopediaRoute,
} as any)
const EncyclopediaIdRoute = EncyclopediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EncyclopediaRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/knowledge/$slug',
  path: '/knowledge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/diagnose': typeof DiagnoseRoute
  '/encyclopedia': typeof EncyclopediaRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/community/$id': typeof CommunityIdRoute
  '/community/new': typeof CommunityNewRoute
  '/encyclopedia/$id': typeof EncyclopediaIdRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/encyclopedia/': typeof EncyclopediaIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/diagnose': typeof DiagnoseRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/community/$id': typeof CommunityIdRoute
  '/community/new': typeof CommunityNewRoute
  '/encyclopedia/$id': typeof EncyclopediaIdRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/community': typeof CommunityIndexRoute
  '/encyclopedia': typeof EncyclopediaIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/diagnose': typeof DiagnoseRoute
  '/encyclopedia': typeof EncyclopediaRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/community/$id': typeof CommunityIdRoute
  '/community/new': typeof CommunityNewRoute
  '/encyclopedia/$id': typeof EncyclopediaIdRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/encyclopedia/': typeof EncyclopediaIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/diagnose'
    | '/encyclopedia'
    | '/login'
    | '/me'
    | '/privacy'
    | '/sitemap.xml'
    | '/community/$id'
    | '/community/new'
    | '/encyclopedia/$id'
    | '/knowledge/$slug'
    | '/community/'
    | '/encyclopedia/'
    | '/knowledge/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/diagnose'
    | '/login'
    | '/me'
    | '/privacy'
    | '/sitemap.xml'
    | '/community/$id'
    | '/community/new'
    | '/encyclopedia/$id'
    | '/knowledge/$slug'
    | '/community'
    | '/encyclopedia'
    | '/knowledge'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/diagnose'
    | '/encyclopedia'
    | '/login'
    | '/me'
    | '/privacy'
    | '/sitemap.xml'
    | '/community/$id'
    | '/community/new'
    | '/encyclopedia/$id'
    | '/knowledge/$slug'
    | '/community/'
    | '/encyclopedia/'
    | '/knowledge/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DiagnoseRoute: typeof DiagnoseRoute
  EncyclopediaRoute: typeof EncyclopediaRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CommunityIdRoute: typeof CommunityIdRoute
  CommunityNewRoute: typeof CommunityNewRoute
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia': {
      id: '/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/new': {
      id: '/community/new'
      path: '/community/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof CommunityNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia/': {
      id: '/encyclopedia/'
      path: '/'
      fullPath: '/encyclopedia/'
      preLoaderRoute: typeof EncyclopediaIndexRouteImport
      parentRoute: typeof EncyclopediaRoute
    }
    '/encyclopedia/$id': {
      id: '/encyclopedia/$id'
      path: '/$id'
      fullPath: '/encyclopedia/$id'
      preLoaderRoute: typeof EncyclopediaIdRouteImport
      parentRoute: typeof EncyclopediaRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/knowledge/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EncyclopediaRouteChildren {
  EncyclopediaIdRoute: typeof EncyclopediaIdRoute
  EncyclopediaIndexRoute: typeof EncyclopediaIndexRoute
}

const EncyclopediaRouteChildren: EncyclopediaRouteChildren = {
  EncyclopediaIdRoute: EncyclopediaIdRoute,
  EncyclopediaIndexRoute: EncyclopediaIndexRoute,
}

const EncyclopediaRouteWithChildren = EncyclopediaRoute._addFileChildren(
  EncyclopediaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DiagnoseRoute: DiagnoseRoute,
  EncyclopediaRoute: EncyclopediaRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CommunityIdRoute: CommunityIdRoute,
  CommunityNewRoute: CommunityNewRoute,
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
